### ISSUE TITLE
Deeper Docker / K8s integration.

### ISSUE THREAD

**Issue by PhilsLab** [pydio/cells#104]
I'd love to see deeper support for docker and k8s deployments, by implementing features such as:

- First-time setup via environment variables or YML bootstrap config (e.g. a k8s config map)
- Ability to replicate pydio instances safely in front of a k8s service/loadbalancer (k8s replicaCount)
- Redis/KeyDB cache integration for static assets and frequently requested data
- S3-Only storage option (relates to #102 )
- Community edition SAML integration - Many self-hosters have IdPs such as Keycloak for simpler account management.

This would help Pydio a lot in terms of scalability and cloud-readiness.

How's the opionion on those topics?

**Comment by xserve98** [comment]
There are plans to update go-micro, GRPC?

**Comment by cdujeu** [comment]
Hi, thanks for posting.
We do have to provide more resources for K8s integration. Community-contribs are more than welcome on that topice.
Regarding upgrades of go-micro & grpc, no specific plans at this time, until we move on to go modules probably. We have a working vendor setup, and it's really the best we can do. Any specific reasons for this request?

**Comment by equbit** [comment]
We are still waiting for deployment files to Kubernetes ;)

**Comment by lukasmrtvy** [comment]
@PhilsLab Totally valid points !

**Comment by suhas316380** [comment]
> We are still waiting for deployment files to Kubernetes ;)

I was able to setup Pydio Cells on EKS and baremeta based on [this doc](https://pydio.com/en/docs/cells/v2/launching-docker)
[pydio-cells-basic-k8s-setup.yml.txt](https://github.com/pydio/cells/files/5361772/pydio-cells-basic-k8s-setup.yml.txt)

. Including basic manifest here that sets up:
1. mysql deployment (5.7) and service.
2. Pydio Cells deployment and service (listens on 443) of type LoadBalancer

Steps:
- Create mysql secret (change the values!): `kubectl -n test create secret generic mysql-secret --from-literal=MYSQL_ROOT_PASSWORD=pydio --from-literal=MYSQL_DATABASE=cells --from-literal=MYSQL_USER=pydio --from-literal=MYSQL_PASSWORD=pydio
- Apply the manifest.
- If you don't have a domain name, replace "storage.example.com" in the manifest with either Public/Private IP of your node.
- If using EKS, a public LoadBalancer will be created. Once that is created, replace "storage.example.com" with the LoadBalancer DNS name

Testing:
- Curl the ClusterIP of pydio cells Pod/Service: `curl -sSk https://<ip> -H 'Host: storage.example.com'`

**Comment by SeWieland** [comment]
I'm completely new to pydio, but very interested in this issue as well..
Actually I'm searching for some kind of "cloud-ready Nextcloud alternative" for my private setup (for now).

I stumbled upon pydio cells and specifically your [microservice approach](https://www.pydio.com/en/docs/cells/v3/pydio-cells-internals), which looks like quite the perfect fit!

However, I somehow expected all services to be packaged separately. This way, one could create a nice little helm-chart bundling everything together, without losing the ability to deploy and scale each service independently.

With only one Docker image available, I'm not sure at all, how you'd scale the service efficiently. Is this one container even meant to be replicated at all?

**Comment by cdujeu** [comment]
if you are still interested, please deep dive in the forthcoming v4 (rc's are available, docs coming very soon). Most of the initial OP suggestions are implemented.
