### ISSUE TITLE
Could not find Datasource

### ISSUE THREAD

**Issue by dikdableu** [pydio/cells#108]
I am trying to add a local directory from the server to Pydio Cells. 

For that I add a storage and a workspace but when I try to access the workspace I have the error "could not find datasource <name directory>"

![image](https://user-images.githubusercontent.com/11444731/56198581-78f26800-603b-11e9-9269-2c1f075b67da.png)

I have a Cocker pydio/cells 
I'm in Pydio cells Home edition 1.4.1

**Comment by cdujeu** [comment]
Hi, please post to the forum instead https://forum.pydio.com
Thx!
