### ISSUE TITLE
Standard users unable to set visibility on a public share

### ISSUE THREAD

**Issue by fajo-de** [pydio/cells#111]
Standard (and shared) users are not authorized to change visibility on public shares. This is caused by the Ladon policy "_user-ws-readonly_"  which explicitly denies PUT access to "_rest:/workspace/<.+>_" for this user classes.

**_To replicate the issue:_**

1. create a public share on a folder
2. after saving the link choose the "Visibility" tab
3. check the box for "View" for the "Root Group"
4. click save

**_Server logs:_**

`Apr 25 01:56:05 srpapp11-defrl cells: {"level":"error","ts":"2019-04-25T01:56:05+02:00","logger":"pydio.rest.workspace","msg":"Ladon blocked PUT request at /workspace/test-folder. Ladon Response: ExplicitDeny:true","SpanUuid":"85bcba00-66ec-11e9-9137-782bcb00e5bd","RemoteAddress":"n.n.n.n","UserAgent":"Mozilla/5.0...","ContentType":"application/json","HttpProtocol":"HTTP/1.1","UserName":"testuser","UserUuid":"58438fd9-59e0-46ed-b474-41786abf3034","GroupPath":"/","Profile":"standard","Roles":"ROOT_GROUP,58438fd9-59e0-46ed-b474-41786abf3034"}`

**_Request Data:_**

`Request URL     : https://cells/a/workspace/test-folder
Request method  : PUT
Remote address  : n.n.n.n:8080
Status code     : 401
Version         : HTTP/1.1
Referrer Policy : no-referrer-when-downgrade

**_Params:_**

    Attributes	{"DEFAULT_RIGHTS":""}
    Description	Created on 2019/04/25
    Label	Test Folder
    LastUpdated	1556146659
    Policies	[…]
        0	{…}
            Action	OWNER
            Effect	allow
            id	9
            Resource	5be20932-66e4-11e9-8658-782bcb00e5bd
            Subject	58438fd9-59e0-46ed-b474-41786abf3034
        1	{…}
            Action	READ
            Effect	allow
            id	10
            Resource	5be20932-66e4-11e9-8658-782bcb00e5bd
            Subject	user:testuser
        2	{…}
            Action	WRITE
            Effect	allow
            id	11
            Resource	5be20932-66e4-11e9-8658-782bcb00e5bd
            Subject	user:testuser
        3	{…}
            Action	WRITE
            Effect	allow
            id	12
            Resource	5be20932-66e4-11e9-8658-782bcb00e5bd
            Subject	profile:admin
        4	{…}
            Action	READ
            Effect	allow
            id	13
            Resource	5be20932-66e4-11e9-8658-782bcb00e5bd
            Subject	user:5be8223f66e411e9
        5	{…}
            Action	READ
            Effect	allow
            Resource	5be20932-66e4-11e9-8658-782bcb00e5bd
            Subject	role:ROOT_GROUP
    PoliciesContextEditable	true
    RootNodes	{…}
        b761c55b-8c97-4d49-b5b1-a220cac686c0	{…}
        Etag	98c790aea29c94ff4690963bc40bb98b
        MetaStore	{…}
            name: "Test Folder"
        MTime	1556146653
        Path	personal/testuser/Test Folder
        Size	36
        Type	COLLECTION
        Uuid	b761c55b-8c97-4d49-b5b1-a220cac686c0
    Scope	LINK
    Slug	test-folder
    UUID	5be20932-66e4-11e9-8658-782bcb00e5bd`

**Comment by cdujeu** [comment]
Hi @fajo-de, thanks for reporting.

The policy was added prevent users for creating a workspace wherever they wanted to. Even if "shares" generate workspaces under the hood, standard users currently only manage them via the dedicated /idm/share API (which is secured by checking ACLs).
So I guess we have two options here
- Manage the shares visibility via the /share API instead of the /workspace API - (leaving the /workspace API editable to admins only).
- Re-open the workspace API for RW to standard users, but add additional checks in this API to make sure user can edit/create a workspace at a given location.

There are pros and cons for both, we'll discuss that internally, any thought?  
-c

**Comment by fajo-de** [comment]
Hi @cdujeu ,

I would suggest to move that functionality into the /share API. It alters shares, so I would prefer this over securing the /workspace API. Securing the latter could probably be easier to implement by just allowing write access to standard users in case of "Scope" is set to "LINK"? This could eventually be used as a temporary workaround.

Cheers,
Falk

**Comment by cdujeu** [comment]
Should be fixed by a8e896853fea6be1bee0a1554821307568cd6020
