### ISSUE TITLE
FreeBSD: deps.sh needs /usr/local/bin/bash, not /bin/bash

### ISSUE THREAD

**Issue by GwynethLlewelyn** [pydio/cells#113]
Hello there,

I'm compiling Cells from scratch on a FreeBSD box, and while everything works so far, I've noticed that `deps.sh` presumes that, by default, `bash` is located in `/bin/bash`. This is true for most Linuxes and for macOS — but not for FreeBSD, which has it in `/usr/local/bin/bash`.

This is a very tiny fix, requiring (possibly) an automatic generation of the `deps.sh` file using something akin to ``which `bash` `` to create the first line, or, eventually, using `#!/usr/bin/env $SHELL` at the top of the script ([inspired by this issue on StackExchange](https://unix.stackexchange.com/questions/66210/how-can-i-have-more-than-one-possibility-in-a-scripts-shebang-line)), which, however, will fail if `bash` is _not_ the shell for this particular user... (note that `/usr/bin/env` seems to be a location consistently used by Linux, macOS, _and_ FreeBSD).

**Comment by cdujeu** [comment]
Hi @GwynethLlewelyn 
Thanks for reporting! Actually I'm not even sure we still need this script at all since we use vendoring instead. I'll check, maybe the readme needs an update as well...
-c

**Comment by GwynethLlewelyn** [comment]
> Hi @GwynethLlewelyn
> Thanks for reporting! Actually I'm not even sure we still need this script at all since we use vendoring instead. I'll check, maybe the readme needs an update as well...
> -c

Cool! 👍 Well, in my case, it certainly didn't hurt to run it...

**Comment by bsinou** [comment]
OK. I've checked and removed the `deps.sh` file. I have updated the README accordingly.
Closing this for now.
