### ISSUE TITLE
FreeBSD: github.com/zalando/go-keyring requires keyring.MockInit()

### ISSUE THREAD

**Issue by GwynethLlewelyn** [pydio/cells#115]
In my attempts to get Cells running under FreeBSD, the first thing I needed to change was keyring access. `github.com/zalando/go-keyring` only supports Linux, macOS and Windows. However, they provide a `MockInit()` function which allows a 'fake' keyring to be created even if the underlying OS does not support it.

This means that all that is required (for FreeBSD and other non-supported OSes) is to change `github.com/pydio/cells/common/crypto/keyring.go` to call `keyring.MockInit()` just after each function in that file.

One possibility would be to add a line to figure out what underlying OS is running (after all, Zalando's `go-keyring` works like that), and if none of the supported ones is detected, call `MockInit()` automatically.

**Comment by cdujeu** [comment]
Thanks for this report too. Would be really nice to support compil on FreeBSD. As this lib is relying on underlying tools being installed on the OS, we already have an alternative solution for making our own keychain, so I thought it would be cross-os by default.

**Comment by GwynethLlewelyn** [comment]
> Thanks for this report too. Would be really nice to support compil on FreeBSD. As this lib is relying on underlying tools being installed on the OS, we already have an alternative solution for making our own keychain, so I thought it would be cross-os by default.

Actually, no, or perhaps 'not yet', since Zalando's `go-keyring` also does not support FreeBSD directly, but, fortunately, they have considered the lack of OS-specific support and implemented `MockInit()`  to deal with those unsupported OSes... but since you're forking them... maybe in the future you can add some extra functionality to deal with the issue (e. g. see if `go-keyring` directly supports 'native+ keyrings, and, if not, call `MockInit()`).

I'm afraid I'm too much of a Go newbie (but learning!), not to mention a Cells newbie, to be able to offer a 'permanent' solution — all I can do is quick & dirty patching! 😹

On the other hand, I _did_ manage to get Cells installed on FreeBSD  😉There are some nagging details at the CLI level (e. g. delete/backspace rarely works) but in general things work quite well overall!
