### ISSUE TITLE
"Demo feedback" button.

### ISSUE THREAD

**Issue by RCanaro** [pydio/cells#116]
The demo instructions stated:

> During your demo, you can leave us feedback / improvement ideas by clicking on the "Demo feedback" button.

but I can't find a similar button in the page.

**Comment by AngelFr** [comment]
<img width="430" alt="Capture d’écran 2019-05-12 à 16 51 36" src="https://user-images.githubusercontent.com/10709076/57586489-ea1c2280-74f6-11e9-8c1b-65cfb2aad300.png">
It's on the online demo

**Comment by RCanaro** [comment]
Thank you.
I was searching in the online demo, but I thought it was a button in the dashboard or console.
C:
