### ISSUE TITLE
DB user password stored in plain text

### ISSUE THREAD

**Issue by RCanaro** [pydio/cells#117]
The DB user's password of my Cells instance:

> Pydio Cells Home Edition (1.5.2)
> Published on 07 May 19 15:04 +0000
> Revision number 4ae5255e1b28b01d9dea14ec1b386069194aa547

is stored in the pydio.json file as plain text:

```
  "databases": {
    "a6da927d65062158ac569fcf0ae9b64ada3dfc26": {
      "driver": "mysql",
      "dsn": "pydio:pwd-revealed@tcp(localhost:3306)/cells?parseTime=true"
    },
```
is it possible to keep it secret?

Thank you,
C:

**Comment by cdujeu** [comment]
Hello @RCanaro - no not at that point
Your pydio.json should be protected in any case

**Comment by RCanaro** [comment]
Thank you.
