### ISSUE TITLE
Webdav on Cells 1.5.3 is not working anymore

### ISSUE THREAD

**Issue by KungFu-Kenny** [pydio/cells#131]
WebDav does not work on 1.5.3.

**Comment by KungFu-Kenny** [comment]
There is a fix pushed, requires to manually re build a binary

**Comment by GwynethLlewelyn** [comment]
I can confirm that this latest fix makes WebDAV work again under FreeBSD!

**Comment by cdujeu** [comment]
Closed in 1.6
