### ISSUE TITLE
Missing frontend on build

### ISSUE THREAD

**Issue by lutostag** [pydio/cells#136]
Hey there,

First off thanks for a great project. I am attempting to build cells for a raspberry pi (I know the recommended minimum ram is 4GB, but I just want to see how it performs) -- but before I get there I wanted to get the build working on amd64 properly.

I can build the project and it will run (the api endpoints are available), but it is not including the frontend (html/javascript) to be served properly.

The following is the Dockerfile I am using, I assume I am missing something related to `make front` or similar?

```
# handle certificate and downloads in another stage to reduce image size
FROM golang:latest as certs
ARG version

ENV CELLS_VERSION ${version}

RUN go get -u github.com/pydio/cells

WORKDIR /go/src/github.com/pydio/cells
RUN make dev
RUN make ctl

# Creates the final image
FROM busybox:glibc
ARG version

WORKDIR /pydio

ENV CELLS_BIND localhost:8080
ENV CELLS_EXTERNAL localhost:8080

# Add necessary files
COPY docker-entrypoint.sh /pydio/docker-entrypoint.sh
COPY --from=certs /lib/*/libdl*.so.2 /pydio/
COPY --from=certs /etc/ssl/certs /etc/ssl/certs
COPY --from=certs /go/src/github.com/pydio/cells/cells-ctl .
COPY --from=certs /go/src/github.com/pydio/cells/cells .

# Final configuration
RUN ln -s /pydio/cells /bin/cells \
    && ln -s /pydio/cells-ctl /bin/cells-ctl \
    && ln -s /pydio/libdl.so.2 /lib64/libdl.so.2 \
    && ln -s /pydio/docker-entrypoint.sh /bin/docker-entrypoint.sh \
    && chmod +x /pydio/docker-entrypoint.sh

VOLUME ["/root/.config"]
ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["cells", "start"]
```

Any help would be appreciated. Thanks again!

**Comment by cdujeu** [comment]
Hi!
I guess you are missing the ‘make generate’ command, which embeds all statics inside the binary - you may need to go install the gobuffalo/packr to have the packr commmand available 
Best

**Comment by lutostag** [comment]
Indeed, thanks. installing packr and using `make build` rather than `make dev` got it for me. Thanks!
