### ISSUE TITLE
Running the example returns "cURL error 7 connection refused"

### ISSUE THREAD

**Issue by vabatta** [pydio/cells#14]
Hi,

Just by running locally the example using docker-compose provided in the description doesn't let you login by giving the error "cURL error 7 connection refused".

What's wrong?

**Comment by vabatta** [comment]
Can't you pack up the docker image with the php as official Docker images (for example, wordpress)?

**Comment by ghecquet** [comment]
Hi there,

Can you please use the pydio forum for help on a setup issue ? (https://pydio.com/fr/docs/developer-guide/reporting-bugs)

As for the official docker image, it's a long process.. be patient :)

Thanks,
Greg
