### ISSUE TITLE
https://pydio.com/fr/docs/cells/v1/run-behind-proxy 404

### ISSUE THREAD

**Issue by gerroon** [pydio/cells#140]
Hi

This page does not exists

https://pydio.com/fr/docs/cells/v1/run-behind-proxy

`ERROR #404 Page non trouvée`

**Comment by cdujeu** [comment]
Hi, 
Yes the page has been moved from admin guide to various knowledge base articles : https://pydio.com/fr/docs/kb/devops

Can you point me where you got the link? I mean where is there a broken link ? 
Thx

**Comment by gerroon** [comment]
Hi

I do not remember the exact location atm but I am sure it was from one of your documentation pages. I will try to find it later. I think I was trying to find more about Cells Docker and Apache

**Comment by cdujeu** [comment]
Please open an issue in the docs repository  if you find the dead link :)
