### ISSUE TITLE
Issues about search functionality

### ISSUE THREAD

**Issue by mtrstudio** [pydio/cells#141]
Pulled the latest pydio cell from docker, and tried it. It is quite good in many ways. But I found two undesirable things about searching:

1. No full-text search ( Don't know if this will be included in future releases )

2. Search by meta data does not work as normally expected -- search order matters! Seems to be a bug!
For example, suppose we have the following files:

docAA (meta: tag1)
docBB (meta: tag2, tag1)
docCC (meta: tag2, tag1, tag3) 

Now you want to find files with tag1, tag2 and tag3.

Search _tag2, tag1 and tag3_ gives **docCC** (Correct)

BUT search _tag2 tag3 and tag1_ gives **NOTHING** ( Wrong, should give docCC as above )

**Comment by cdujeu** [comment]
1. Regarding content indexation
We have an experimental feature to do that, not thoroughly tested though. We use https://github.com/sajari/docconv, so check their readme for the required dependencies. Then add the `"indexContent": true` parameter inside your config for the pydio.grpc.search service.

2. That's interesting, indeed metadata are indexed as full text - we would have to dig more to fix that.

**Comment by cdujeu** [comment]
I cannot reproduce that issue with tags - searching with [tag3], [tag3] [tag1] in any orders is giving good results. Please re-open if required.
