### ISSUE TITLE
WebDAV "MOVE" and "COPY" are not working

### ISSUE THREAD

**Issue by manuth** [pydio/cells#142]
Dear cells-team
I just noticed that "MOVE" and "COPY"-requests always result with an error in the pydio-logs:
```
Aug 19 14:02:25 nuth-plesk cells[19091]: 2019-08-19T14:02:25.833Z        ERROR        pydio.gateway.dav        |- DAV END        {"method": "MOVE", "path": "/dav/personal-files/Documents/Keys/KeyDatabase.kdbx", "destination": "/dav/personal-files/Documents/KeyDatabase.kdbx", "error": "webdav: invalid destination"}
```

Is there some way to get this to work?
I'm running cells behind a nginx-proxy.

**Comment by cdujeu** [comment]
First, just to make sure, is you Cells up-to-date? We had issues with that at one point but after that it was fixed.
If it's up-to-date, it's probably a proxy issue - did you check if there was anything about that in the doc?

**Comment by manuth** [comment]
Well, yeah, the docs said something like redirecting the "WebDAV"-headers using a `transparent`-directive...?

Anyway while nginx and my WebDAV-client weren't reporting any useful errors.
My DAV-client (WinSCP) and the nginx-logs both are reporting "502 Bad Gateway"-errors while Cells did come up with some more verbose errors (refer to my first post).



Cells is up to date and my proxy-settings look following:
```nginx
location / {
	proxy_buffering off;
	proxy_pass http://localhost:3012$request_uri;
	proxy_pass_request_headers on;
	proxy_set_header X-Real-IP $remote_addr;
}

location /ws {
	proxy_buffering off;
	proxy_pass http://localhost:3012;
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection "upgrade";
	proxy_read_timeout 86400;
}
```

**Comment by manuth** [comment]
@cdujeu as you can see in the code of the `golang` project, a "502 Bad Gateway" occurs in the following case:
https://github.com/golang/net/blob/1492cefac77f61bc789c00f41ead8f8d7307cd21/webdav/webdav.go#L326-L328

So basically the `Host` is incorrect...? This definitely means the nginx-settings need to be refactored.

Do you have any idea on what to do?

**Comment by manuth** [comment]
I tried to fix it by adding this expression to my ngnix-config:
```nginx
	proxy_set_header Host $host;
	proxy_set_header X-Forwarded-For $remote_addr;
```
Sadly this caused pydio to not work anymore:
```
404 Site cloud.nuth.ch is not served on this interface
```

I guess you guys need to rework pydio to not cause the error at this piece of code:
https://github.com/golang/net/blob/1492cefac77f61bc789c00f41ead8f8d7307cd21/webdav/webdav.go#L326-L328

E.g. update the host-part of either the request or the header before passing it to `golang`'s webdav-handler.

**Comment by cdujeu** [comment]
Hi, 
Just back from vacations.
Did you check that your reverse proxy is correctly forwarding the Destination header? It's a WebDAV specific header for COPY/MOVE operations.
This should be working correctly

**Comment by manuth** [comment]
Hi @cdujeu
Hope you had a great stay!
I made it sure by sniffing the backend (localhost:3012) on my server. The destination-header is set correctly.

I could also make sure that the `502 Bad Gateway` error occurrs when the host in the Destination-header (which is, in my case, `cloud.nuth.ch`) and the host the request is addressed to (which is `localhost:3012`) don't match.

Sadly I cannot change the host of the request because this ends up in a `404 Site cloud.nuth.ch is not served on this interface`-error.

I also can't manipulate the `Destination`. I don't know whether nginx provides a feature like this.

**Comment by manuth** [comment]
I have a workaround people may want to use until this issue is solved:
I added this to my ngnix-config:

```nginx
location /dav {
	set $destination $http_destination;
	proxy_buffering off;
	proxy_pass http://localhost:3012$request_uri;
	proxy_pass_request_headers on;
	proxy_set_header X-Real-IP $remote_addr;

	if ($destination ~* "^(.*://)cloud\.nuth\.ch(:\d+)?(.*)$") {
		set $destination "http://localhost:3012$3";
	}

	proxy_set_header Destination $destination;
}
```

This piece of code rewrites the `Destionation`-header. The front-end address (`cloud.example.com`) is replaced by the back-end address (`http://localhost:3012`).

**Comment by cdujeu** [comment]
closing, as it's a proxy config
