### ISSUE TITLE
Which version of protoc is used to generate files in common/proto?

### ISSUE THREAD

**Issue by xserve98** [pydio/cells#144]
Which version of protoc is used for generating the protobuf stubs? I can’t find it anywhere in the codebase. Thanks.

**Comment by cdujeu** [comment]
```
protoc --version
libprotoc 3.3.0
```
We are still thinking about a way to share the "official" protoc and protoc plugins in a centralized place to ease that process.
Any hint about why you need to recompile the protobufs?
