### ISSUE TITLE
Add option to specify config directory, to make this more Linux friendly

### ISSUE THREAD

**Issue by r7l** [pydio/cells#145]
Cells is using the current users home directory. This is not good solution for a software running as a service. I would like to be able to place it in /etc/cells.

Please add at least an option like `--config` to specify a custom config directory, that will only hold config files. And even if this directory does contain more then just configs, it should still be possible to set a custom place for it.

**Comment by cdujeu** [comment]
Yep it's in the roadmap - We have to pass configs for a correct linux layout (etc, var, logs, etc..)

**Comment by r7l** [comment]
Thanks. This is good news.

**Comment by cdujeu** [comment]
Added in master, using additional ENV parameters

- `CELLS_WORKING_DIR` => defaults to OS-specific App Data dir (~/.config/pydio/cells on linux for example)
- `CELLS_DATA_DIR` => defaults to `CELLS_WORKING_DIR/data`
- `CELLS_LOG_DIR` => defaults to `CELLS_WORKING_DIR/logs`
- `CELLS_SERVICES_DIR` => defaults to `CELLS_WORKING_DIR/services`
