### ISSUE TITLE
Preview thumbs for PSD images

### ISSUE THREAD

**Issue by Guisardo** [pydio/cells#146]
Hi there,
Is there any way to enable PSD image previews?
Best,

**Comment by cdujeu** [comment]
Hi,
No not yet, I guess we would have to integrate with Image Magick in some way
Definitely a good feature to add !

**Comment by psk-sudo** [comment]
Would this allow for PDF thumbs too? Noticing this is not available either.

**Comment by adigh** [comment]
no updates regarding this?
