### ISSUE TITLE
MySQL port for pydiocells on Docker

### ISSUE THREAD

**Issue by ypapouin** [pydio/cells#148]
How can I set a MySQL port different from 3306 for the pydio/cells image ?

**Comment by ypapouin** [comment]
Ok found it, you can set MySQL server address (docker0 interface) and port at first start when installing pydiocells

**Comment by cdujeu** [comment]
@ypapouin FYI, it would have been better to post in the Forum, we try to keep Github issues only for "qualified" bugs, 
thx!
