### ISSUE TITLE
Change password / edit own profile fails when "Create external users" is off (core.auth)

### ISSUE THREAD

**Issue by fajo-de** [pydio/cells#154]
When switching "Create external users" of in plugin core.auth, users are no longer able to edit their own profile (language, ...) or change their password. They receive "you are not allowed to create users".

`Sep 30 23:13:07 XXXXXXXX cells: {"level":"error","ts":"2019-09-30T23:13:07+02:00","logger":"pydio.rest.user","msg":"Rest Error 403","SpanUuid":"1914538f-e3c7-11e9-984e-782bcb00e5c6","RemoteAddress":"n.n.n.n","UserAgent":"Mozilla/5.0","ContentType":"application/json","HttpProtocol":"HTTP/1.1","UserName":"user-test","UserUuid":"da8ee1b2-6b34-4e66-9009-ac0080c14a36","GroupPath":"/test/","Profile":"standard","Roles":"ROOT_GROUP,6470bf37-18fe-459d-a1dd-e0eebc13b3a5,da8ee1b2-6b34-4e66-9009-ac0080c14a36","error":"you are not allowed to create users"}`

There appears to be an issue in "PutUser" in "idm/user/rest/rest.go" as the part of code that throws this REST error should never be reached if a users updates his own profile.

I was able to replicate this issue at demo.pydio.com

**Comment by cdujeu** [comment]
nice one, thx for reporting

**Comment by scottbentley** [comment]
+1 on this bug

**Comment by cdujeu** [comment]
as mentioned in the "closed" status => fixed in master - please try 2.0.0-rc2

**Comment by scottbentley** [comment]
Auto updater isn’t upgrading to the 2.x release. Any chance of a patch for the 1.x branch?
