### ISSUE TITLE
Watch for "modification" also triggers notification on "access"

### ISSUE THREAD

**Issue by fajo-de** [pydio/cells#155]
Due to a incomplete  implementation a notification is triggered on node "access" even though a watch is set for "modification" only.

I already created a pull request https://github.com/pydio/cells/pull/103 on this with the required change to fix/complete this functionality.

**Comment by cdujeu** [comment]
Hey @fajo-de 
currently looking at this. Is your PR supposed to actually fixed this issue? It seems like it's still not working for me
-c

**Comment by fajo-de** [comment]
Hi @cdujeu ,
it is supposed to fix the issue. I tested against versions up to 1.6.1 and it does what it is expected to. Have you tried with a fresh node without other watches on parent nodes? Otherwise the parents watch may supersede the nodes watch.
Just tested again and it works as expected.
Cheers ,
Falk

**Comment by cdujeu** [comment]
👍

**Comment by cdujeu** [comment]
ok PR is merged thx!
