### ISSUE TITLE
Watch and Share icons not showing up in Detail mode

### ISSUE THREAD

**Issue by fajo-de** [pydio/cells#160]
Hi @cdujeu,
while re-testing (v1.6.1) the watch functionality I found that in _Detail_ display mode the node icons for active _Watch_ or _Share_ are not shown. In _List_ mode and _Thumbnail_ modes it shows up.
Cheers,
Falk

**Comment by cdujeu** [comment]
mm, you're right. I guess we should either add a dedicated column, or maybe add this info just after the file title ... ? 
And BTW the display for medium and small thumbs is not really optimized

**Comment by fajo-de** [comment]
A dedicated column shown right most would probably fit best as this is where the symbols show up in list mode as well ... would be best for user experience.
