### ISSUE TITLE
v2.0.0-rc1 breaks installations with mysqld 5.6

### ISSUE THREAD

**Issue by fajo-de** [pydio/cells#164]
Hi @cdujeu ,

Just tested v2.0.0-rc1 (from git). During start up the below error message appeared:

`Oct 16 21:08:36 pydio cells: failed to initialize storage: failed to open migrations: creating dex_migration table: Error 1193: Unknown system variable 'transaction_isolation'`

and Cells does not start up but continues to restart the proxy service.

Checking the code I found the transaction settings to use the "transaction_isolation" variable introduced in MySQL 5.8. Unfortunately my installation is - as was required by cells v1.x - using MySQL 5.6. In MySQL 5.6 the parameter name is tx_isolation.

**Comment by fajo-de** [comment]
SELECT VERSION() returns: 5.6.46-log which will not match the regex (idm/auth/web/plugins.go) used due to the trailing "-log"

**Comment by cdujeu** [comment]
Thanks! @ghecquet can you have review and merge the PR if ok ?

**Comment by cdujeu** [comment]
pr merged
