### ISSUE TITLE
Faulty settings in pydio.json when setting up Mailer

### ISSUE THREAD

**Issue by tbleiker** [pydio/cells#169]
I encountered some weird behavior when configuring the mailer. I set up everything for smtp and `Send a test email` worked, but only for the first time, then I got the 535 authentication error. I checked pydio.json and saw that in the port field, the host was attached to the port number. I configured pydio.json directly and after a restart of the cells server, everything worked as expected. 

In order to double check, I set the mailer to sendmail and applied the settings. The pydio.json was changed accordingly. I then configured smtp again and after saving the changes, the pydio.json look good. However, I got the 535 authentication error again. I entered the password directly in the pydio.json, restarted the server and it worked again.

I am using the pydio/cells:pre-release docker image: Pydio Cells Home Edition (2.0.0-rc2), Revision number 4cb0d00b29564d49077e9ba1fcd039c088dd093a

**Comment by cdujeu** [comment]
> the host was attached to the port number
what do you mean exactly ? No semi-column between host and port?

**Comment by tbleiker** [comment]
In my case it was "587mail.infomaniak.com", as far as I can remember... Not sure about the semi-column though. What seemed strange to me, was that I could not reproduce this concatenating.

**Comment by cdujeu** [comment]
Closing as probably fixed since then, re-open if needed
