### ISSUE TITLE
Peer address for data sources changes when using docker

### ISSUE THREAD

**Issue by tbleiker** [pydio/cells#170]
I am using the docker image. On each start up, I have to reassign the peer address for each data source because the node cannot be found anymore. This is because the peer address can be either set to the container id or the ip address. When starting the image, however, docker assigns a random id and ip address to the container.

**Comment by tbleiker** [comment]
Maybe it is possible to add the host name as additional peer address?

**Comment by tbleiker** [comment]
Oh boy... i came across the (already quite old) issue https://github.com/pydio/cells/issues/57 and was shocked to realise that I forgot to set the hostname in the docker comopose file and hence, the hostname defaulted to the id... This is already implmented!

I close, hereby, my monologue and apologise for unnecessarily spamming the issue tracker 😄

**Comment by cdujeu** [comment]
:-)
