### ISSUE TITLE
Can docker starts with custom ssl certificate?

### ISSUE THREAD

**Issue by tinymins** [pydio/cells#18]
I'v got a valid ssl certificate, in interactive mode install I can input my own certificate file path. But I cannot pass it to docker when create a new container. Seems in docker we can only use self signed certificate or no-ssl.

Maybe we should create a parameter to pass certificate path when start docker?

**Comment by ghecquet** [comment]
Hi,

Closing this as you've already submitted a PR with that change. Please give us time to review it and merge it in.

Thanks,
Greg
