### ISSUE TITLE
Implement region selection for S3 storage

### ISSUE THREAD

**Issue by Arno500** [pydio/cells#182]
When adding a S3 storage on Pydio, it is currently impossible to set the destination region of the bucket. This may be needed on some S3-compatible storages like Scaleway for instance. Now, Scaleway refuses the connection, because the "region" key in the config.json of Minio is not set (and setting it doesn't work, since the file is overriden each time), thus sending "us-east-1".

A simple solution would be to add a field on the interface, for setting the region. Then, the result would be propagated to Minio's config in the "region" key.

**Comment by cdujeu** [comment]
Hello @Arno500 
Thanks for this feedback, definitely a good parameter to add in the interface.

**Comment by cdujeu** [comment]
hello @Arno500 , i'm trying to implement that but cannot get the gateway to use the proper region. Did you actually succeed in starting a minio gateway with a custom region? It's probably because we use a forked version of minio, but just to make sure ...

**Comment by Arno500** [comment]
No, I didn't try it. After digging deeper, I'm not sure the region setting in the JSON is to set the region of the bucket to connect to, it may be the region the Minio gateway exposes (but I may be completely wrong, though...).
I found this issue: https://github.com/minio/minio/issues/7044#issuecomment-454015419 . They are talking about MINIO_REGION env variable, but this doesn't really seem practical at all... Aaaand, after another check, it seems this setting is not honoured when not using AWS.
A PR fixed that the 29th of May: https://github.com/minio/minio-go/pull/1113

**Comment by cdujeu** [comment]
i digged that this afternoon
and commited a fix ;-)
If you wish to build from master, feel free !

**Comment by cdujeu** [comment]
(it required an update of our fork the minio-go client indeed)
