### ISSUE TITLE
Where is the video-annotation-comments plugin source code?

### ISSUE THREAD

**Issue by alexkruts2** [pydio/cells#183]
Hello sir.
I am going to use video-annotation-comments plugin in your pydio-cells source code.
when I test demo.pydio.com,I can see my browser download the videojs-annotation-comments.js file.
so I think you have the video annotation plugin.
But, After I download your source code, I could not found the plugin.
How can I find that?
thanks.
Regards.
Alex.

**Comment by cdujeu** [comment]
Hello @alexkruts2 
This is feature has been implemented in the Cells Enterprise edition (which is the one used for the demo). 
If you have developer skills, you can have a look at the editor.video JS plugin (under frontend/front-srv/assets/editor.video) to plug the videojs annotation plugin here.
Best
