### ISSUE TITLE
Can't upload any file with spaces in it

### ISSUE THREAD

**Issue by Arno500** [pydio/cells#185]
Pretty self explanatory ! 😄 

You should be able to reproduce the problem with a file named: `03 White ambitions.m4a`, generating this URL: `https://host/io/personal-files/03%20White%20ambitions.m4a?AWSAccessKeyId=gateway&Content-Type=application%2Foctet-stream&Expires=1575590413&Signature=confidentialisuppose%3D`

Note: This is on latest "unstable" (on Docker Hub) as of right now, with an upload to Scaleway S3.

**Comment by Arno500** [comment]
Note: The problem extends to Japanese caracters like `02憧れは流星のように.m4a` (specifically removing spaces) generating `https://host/io/personal-files/02%E6%86%A7%E3%82%8C%E3%81%AF%E6%B5%81%E6%98%9F%E3%81%AE%E3%82%88%E3%81%86%E3%81%AB.m4a?AWSAccessKeyId=gateway&Content-Type=application%2Foctet-stream&Expires=1575590474&Signature=confidentialisuppose%2BXE%3D`

**Comment by cdujeu** [comment]
Two options here : 
- a specific issue with scaleway : do you have similar issues with other datasources? 
- you have a proxy in front of pydio that put some url encoding issues.  
As for the other ticket, can you post in the forum instead? https://forum.pydio.com
Thx
