### ISSUE TITLE
Is it possible to host a pydio cells instance alongside other web apps on the same machine? 

### ISSUE THREAD

**Issue by jcklpe** [pydio/cells#187]
I imagine it is but I'm not really a full on developer. Just a designer who is interested in self hosting.

I've been running a personal nextcloud instance out of my closet for the last year. I'd like to try pydio cells though as the interface seems snappier and better to use.

But I also run a personal wiki on my server and I don't know how to that work with pydio cells. Pydio uses an internal web server as part of its binary right? Something like that right? It's not nginx or apache so how does one set up different routing based on url stuff?

**Comment by cdujeu** [comment]
Hey @jcklpe , could you kindly post this question on the forum instead? We use github issues for qualified bugs only ;-) thx!
https://forum.pydio.com
Charles

**Comment by jcklpe** [comment]
@cdujeu  sure thing, thanks!
