### ISSUE TITLE
ARMv8 support?

### ISSUE THREAD

**Issue by AntoinedeChassey** [pydio/cells#191]
Hey!
Are you guys planning to make a build for ARMv8 (ARM 64 bits) someday?
I see it is on the roadmap for Q4 2019, but I have not found the docker image!
Cheers,
Antoine

**Comment by cdujeu** [comment]
Hello Antoine, 
Yup definitely - It should be available soon, it's just a matter of CI/CD deployment (which is always a bit time-consuming :-) ).
I'll update the roadmap as well

**Comment by AntoinedeChassey** [comment]
Thanks Charles, that's great :)

**Comment by AntoinedeChassey** [comment]
Reopening until released 😄

**Comment by AntoinedeChassey** [comment]
Hi @cdujeu,
Have you had the time to take a look at this?
I tried compiling but got some errors (on MacOS) and did not have the time to dig deeper.
Thx

**Comment by cdujeu** [comment]
nope, not yet. I think we'll go the `xgo` path instead of cross-compil' anyway, it's much safer.

**Comment by bsinou** [comment]
Hello, 

we have re-plugged our arm-64 build for linux and tested it a little bit. I deployed it in AWS cloud on AL2 arm64 EC2 instance to run our test suite against it.

You can find the latest dev build here:  https://download.pydio.com/pub/cells/dev/linux-arm64/cells
Let me know what you think.

PS: there is no packaged image (docker, ami, ...) for this architecture yet.

**Comment by MakerLab-Dev** [comment]
I've tried to run the ARM executable on a Raspberry Pi 4 to test how it does but it says that the format is incorrect. Should it have worked? or RPI4(ARMv8) is not yet supported/tested?

**Comment by cdujeu** [comment]
re-tested and released for arm64

**Comment by aymanbagabas** [comment]
> PS: there is no packaged image (docker, ami, ...) for this architecture yet.

Is there going to be one in the near future?
