### ISSUE TITLE
Error message about folder, while trying to upload an "empty.tex" file

### ISSUE THREAD

**Issue by jxsl13** [pydio/cells#192]
<img width="1436" alt="Bildschirmfoto 2020-01-22 um 23 13 40" src="https://user-images.githubusercontent.com/371944/72939310-e66eba00-3d6c-11ea-88bb-50780db093b2.png">

the file is actually empty.

**Comment by cdujeu** [comment]
Hi
That’s a JavaScript limitation, not much we can do 
Cheers
