### ISSUE TITLE
IE Compatibility Mode Windows Binary

### ISSUE THREAD

**Issue by eccentricly** [pydio/cells#193]
Hello,
I have downloaded and installed the latest Windows Binary for the Pydio Cells. It works perfectly fine in Google Chrome. The company I am installing it in has IE defaulted to IE 7 for legacy pages. I know I need to add `<meta http-equiv="X-UA-Compatible" content="IE=edge">` to the web files … but for the life of me I can’t find them the location on the computer. it is not in the appdata folder unless I am overlooking it. Can someone please help me out? The company wants to see it running in IE before they look into getting enterprise.

**Comment by cdujeu** [comment]
Hi @eccentricly indeed the web files are not "somewhere on the computer", but served directly from within the binary. No way to add an exception directly in the browsers (at least for testing)? We could add something in the code, but that means recompiling and waiting for the next release...

**Comment by eccentricly** [comment]
The way the security is there is no way to add exception to the browsers especially the capacity of the intended test group

**Comment by cdujeu** [comment]
maybe we can provide you a test build to check if it's working - can you wait a couple of days ?

**Comment by eccentricly** [comment]
I can wait a couple of days . Thank you

**Comment by cdujeu** [comment]
you are testing the home version, right?

**Comment by eccentricly** [comment]
That is correct

**Comment by cdujeu** [comment]
i'll pm you

**Comment by eccentricly** [comment]
Hello I am not sure if you received my response. It was a no go.

**Comment by cdujeu** [comment]
got it - sorry no time to make a new build - will do soon

**Comment by eccentricly** [comment]
works thanks
