### ISSUE TITLE
Unable to use cells sync

### ISSUE THREAD

**Issue by Exonip** [pydio/cells#194]
I have got pydio cells (latest version) runninv on my rootserver as a service. Im using an apache proxy and I want to use a nginix proxy for gRPC so I can use cells sync. Im using cloudflare for ssl and olny got ssl setup for my proxy. The cells is running without tls.

If cells is using port 33060 what should I use for my proxy? Can I change the port gRPC is using?
I would appreciate help (:
My Apache host:

<VirtualHost *:443>

  ServerName domain.com
  AllowEncodedSlashes On
  RewriteEngine On

  ProxyPassMatch "/ws/(.*)" ws://xxx.68.111.157:3312/ws/$1 nocanon

  #Finally simple proxy instruction
  ProxyPass "/" "http://xxx.68.111.157:3312/" nocanon
  ProxyPassReverse "/" "http://xxx.68.111.157:3312/" nocanon
  SSLEngine on
  SSLCertificateFile /etc/apache2/ssl/cert.crt
  SSLCertificateKeyFile /etc/apache2/ssl/key.key

  ErrorLog ${APACHE_LOG_DIR}/error-ssl.log
  CustomLog ${APACHE_LOG_DIR}/access-ssl.log combined
</VirtualHost>

My nginix host:
server {
    listen 33060 ssl http2;
    listen [::]:33060 ssl http2;
  ssl_certificate     /etc/apache2/ssl/cert.crt;
  ssl_certificate_key /etc/apache2/ssl/key.key;
  ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers         HIGH:!aNULL:!MD5;
    keepalive_timeout 600s;

    location / {
        grpc_pass grpcs://xxx.68.111.157:33060;
    }

  error_log /var/log/nginx/proxy-grpc-error.log;
  access_log /var/log/nginx/proxy-grpc-access.log;
}

**Comment by jthabet** [comment]
Hello @Exonip ,

The gRPC port is set upon running Cells, either on the command cells start 
- `./cells start --grpc_external=33060`
- or you can also set an env variable for that `PYDIO_GRPC_EXTERNAL=33060` 

The port 33060 is an example value, you can use any port of your choice (make sure that it is not used by another software), make sure if you have a firewall to allow the port.

**Comment by Exonip** [comment]
Hey @jthabet !
First of all, thanks for your help!
But how do I set the gRPC port in the cell sync programm?

**Comment by tbleiker** [comment]
Hey @Exonip,

Have you had a look at their documentation: https://pydio.com/en/docs/cells/v2/run-cells-behind-proxy? Unfortunately, it is not totally up to date, but a good starting point nevertheless! The picture on this post should help you as well: https://pydio.com/en/docs/kb/client-applications/setup-cells-server-cellssync

I have everything running and working behind a Traefik proxy (docker setup). It is important to enable SSL on the cells server in order to get it running.
