### ISSUE TITLE
Restful API

### ISSUE THREAD

**Issue by eccentricly** [pydio/cells#197]
Hello, 
Thank you for your help with the Internet Explorer issue. Now we are trying to test the restful API to generate shared links. The company only uses windows. I am trying to limp through the documentation on the Restful API using the curl. 
The only example provided is a bash example. can you help me get it connected to get a token in windows 10? I keep getting `{"error":"invalid_client","error_description":"Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)","status_code":401}` no matter what I try something is wrong with my translation from bash to batch.

**Comment by jthabet** [comment]
Hello @eccentricly ,

Would you mind sharing the code (do not forget to hide the sensitive data) that you are using.

**Comment by eccentricly** [comment]
`http://SERVER.com:8080/oidc/oauth2/auth?response_type=code&client_id=cells-sync&cells_secret=xxxxxxxxxx&redirect_uri=http://SERVER.com:8080/oauth2/oob&state=1432f199ba`

So I was able to get a new error to show up.... 
`the redirect_uri parameter does not match any of the oauth 2.0 client's pre-registered redirect urls`

**Comment by bsinou** [comment]
Hello, 

the error here is quite explicit: you have to register your client so that the API accept the requests. If you look at the bottom of your pydio.json file on the server, you will see already registered clients that illustrate valid registration.

Thus said, we would really appreciate if you can ask such questions on our [forum](https://forum.pydio.com) rather than here: see [CONTRIBUTING.md](https://github.com/pydio/cells/blob/master/CONTRIBUTING.md) for more info on the subject.

**Comment by eccentricly** [comment]
I have spent the last week trying to get it to work by following the documentation provided. I get that error even using cells-client client ID. 

I feel this is a bug.... and I feel that the documentation should be clearer. I feel it also should provide examples for Windows binary and not just *nix. I would prefer to use a *nix environment. When you work for a Fortune 50 company they don’t let you choose the environment you get to work in.

**Comment by cdujeu** [comment]
@eccentricly we will retry this on windows. Quick question, did you actually *try* to login with cells-client from a *nix platform? That could exclude server configuration out of the way...

**Comment by jthabet** [comment]
Hello @eccentricly ,

Could you try with this client_id `cells-client`, 

Assuming that you did not modify or create an Oauth2 client then you should be using the default parameters, for `cells-sync` the redirect URI are different.

<img width="512" alt="Screenshot 2020-02-03 at 16 33 50" src="https://user-images.githubusercontent.com/32544469/73666556-476a8c00-46a3-11ea-946b-fe1cf2f488b9.png">

**Comment by eccentricly** [comment]
After a fresh install the redirect error went away. New issue now ... how do I allow the auth without https? I get an error that I have to use local host to do it insecurely. Is there away to turn it off to allow it? 

The network is strange at the company ... if I have it set to localhost the site can’t be viewed on other computers.  I have requested a ssl but that could take some time to get it issued for the app and I need to get it running before that time.

**Comment by cdujeu** [comment]
closing as inactive
