### ISSUE TITLE
File shared with cell can be dragged into root folder

### ISSUE THREAD

**Issue by JohanAR** [pydio/cells#20]
Pydio Cells 1.0.4 2018-09-07 (btw. why can't I select and copy text from the about dialog?)

Running in docker containers created by your docker-compose example config, on top of Ubuntu 16.04.5 LTS derivate

Steps to reproduce:
1. Create new empty cell without adding users to share it with
2. Upload a file to Personal Files workspace
3. Select the file and go to Share
4. Choose Add to cell... and select the cell you created before, press save
5. Go to the cell

Unexpected behaviour 1:
- The file has been added as a root folder, instead of inside the existing root folder

Steps to reproduce:
6. Drag the file inside the root folder of the cell

Unexpected behaviour 2:
- The file is renamed with a hash prefix, e.g. "myfile.txt" is changed to "cd5faf34-myfile.txt"

Unexpected behaviour 3:
- The file is removed from the Personal Files workspace (i.e. where you  shared it)

Steps to reproduce:
7. Create one more empty cell
8. On the file you moved into the first cell, select Share
9. Choose Add to cell... and select both the cells you have created
10. Go to the second cell
11. Move the file into the cell's root folder

Unexpected behaviour 4:
- The file is renamed with an additional hash prefix (not as unexpected this time)

Unexpected behaviour 5:
- The file is NOT removed from the first cell (where you shared it) this time. It still exists as a multiple root folder, but with the new longer name

Unexpected behaviour 6:
- The file is not moved in the second cell (where you did the drag and drop) either. It exists both as a multiple root and inside the cell's actual root folder

I guess (1) could be intended behaviour and just seems a bit unintuitive to me. Maybe it's because the system calls it a "root folder" despite being a file and not a folder.

**Comment by cdujeu** [comment]
Hi Johan, 
Thanks for this detailed report :-). For next time, please post in the forum first, we want to first "discuss" in the forum and then we post only qualified issues (one or many) in GH. 
I did not reproduce the whole stuff now, but for 1 to 3 : 
1 - Indeed, the file is in fact another "root" (should not say root folder in that case). When you create an empty cell, a dedicated folder is created for this cell. When you add a file to this cell, it is another root, it is not added to this folder.
2 / 3 : this is a bug imo, you should not be allowed to drag a cell root into something else. The additional prefix is a side-effect from that (roots are "virtual" and we use this hash internally to rebuild proper paths inside cells, if you share two folders with the same name as two roots of a cell).
The fact that you can move it is the same side-effect : the file you move around is really the same as the original one you shared, so if you move it, it disappear from the original workspace :-)

I guess the next steps are side-effects of this as well (should not be allowed to move cells roots around).
Charles

**Comment by JohanAR** [comment]
Will do! Would you like me to change the issue to something like "File shared with cell can be dragged into root folder", or close it so you can open a new issue later if necessary?

**Comment by cdujeu** [comment]
yes, just update the title thx !

**Comment by cdujeu** [comment]
Hi @JohanAR - could you check if we can close this ticket after updating to Cells 1.2.0 ? 
Thx

**Comment by JohanAR** [comment]
I was running Cells in docker, with SQL and PHP in separate containers, and it seems like I have to re-run the installation process after upgrading the Cells image. I had a lot of trouble getting the containers to talk with each other and I can't remember how I got it working the last time. Unfortunately I don't have time to look into it at present, so maybe you can close the issue if you no longer can reproduce it

**Comment by cdujeu** [comment]
Ok i will close that one, but
> it seems like I have to re-run the installation process after upgrading the Cells image
This may be another issue!
