### ISSUE TITLE
Show/Hide "technical roles" checkbox reversed

### ISSUE THREAD

**Issue by drzraf** [pydio/cells#203]
Cells 2.0.3, on /settings/idm/roles

The show/hide "technical roles" checkbox (under the filtering button) is doing the contrary to what is marking the checkbox.
Checking "hide" actually show them and vice-versa.

![Screenshot from 2020-02-25 20-47-59](https://user-images.githubusercontent.com/1169926/75298022-20b9f400-5810-11ea-9a36-a9841ba53761.png)

**Comment by cdujeu** [comment]
Fixed in master - will be pushed soon
