### ISSUE TITLE
[metadata] Filename convention enforcement

### ISSUE THREAD

**Issue by drzraf** [pydio/cells#204]
I suggest the creation of a **plugin** that would provide **filename restriction/enforcement**.

For example, in the “_common_” workspaces:

- directory creation restricted. Eg: only matching \d\d\d\(-\d\d)? for years/month
- uploaders would be restricted in the filenames too according to admin-preferred patterns. The pattern list, order and policy (allow/block/pass) could be created from a UI or imported from a CSV/JSON file.

This would enforce better organization when a large amount of files are shared across numerous users.

Sample use case:
> All user collaborate upload images of mountains or lake having specific date and region. We want to enforce filename as `<year>-(lake|mountain)-<countrycode>-.*.jpg`.

Corresponding forum post:
https://forum.pydio.com/t/feature-filename-convention-enforcement-plugin/3111

**Comment by cdujeu** [comment]
Hi, actually this is doable using security policies, but it is a Cells Enterprise feature
