### ISSUE TITLE
[upload] Inconsistent start/pause button states & UI semantics

### ISSUE THREAD

**Issue by drzraf** [pydio/cells#212]
- [ ] When starting an upload via the modal popup (titled "Standard"), after _Pick_ing a file, the upload starts immediately (no "trash" icon appears), but the red button still shows "_Start_" with a _play_-like triangular button. It's inconsistent because the upload **already started**. This behavior does not happen for subsequent upload in a row or in the case I'm asked for merging.
- When reducing the modal and expanding it again the behavior is "fixed" as it shows a "Pause" button which is correct.
- [ ] If clicking the _Pause_ button, the button disappears but **upload continues**. I can see progress going on in the notification area of the upload and there is no way to pause again.
- [ ] When clicking _Stop_, the progress bar reinitialize for already fully uploaded chunks, but the bar corresponding to partial chunks stays blue at the same percentage.
- [ ] _Stop_ button semantic is confusing. We can indeed "_retry_", but not "_Resume_" again. It acts more like a "Cancel" button and, as such, should probably be given a clearer indicator (or maybe even a confirmation that the dozens of MB already uploaded are going to be discarded).

See also #161

**Comment by ljubomirb** [comment]
there is also "play" icon when watching image... intention behind it is not really clear to see

**Comment by cdujeu** [comment]
Drastically improved - see in master - probably still some glitches
