### ISSUE TITLE
login page modification: add a simple link on this page

### ISSUE THREAD

**Issue by gekigek99** [pydio/cells#214]
i would like to add a very simple link to the left of the enter button (id: 'dialog-login-submit') in the login screen

i know the working dir should be 'frontend\front-srv\assets\core.authfront\res' but i can see 3 different files in this dir that create the enter button: what is the real one?

what code should i use to create a simple link on this page?

**Comment by cdujeu** [comment]
Hello @gekigek99 
you should modify the `LoginPasswordDialog` React component, 
Charles

**Comment by cdujeu** [comment]
Please re-open if necessary, or better post in the forum for non fully qualified issues !
