### ISSUE TITLE
Image slideshow not showing images

### ISSUE THREAD

**Issue by johanneskoester** [pydio/cells#216]
In the web interface, when clicking on a photo, I can see the thumbnail on the top right bar. However, when opening the photo with a double click, the slideshow screen turns on, but no photo is rendered.

**Comment by johanneskoester** [comment]
At the place where the image should probably be, there is an HTML comment in the page source, saying `<!--react-empty:... -->`

**Comment by cdujeu** [comment]
Hello @johanneskoester sorry for the delay...
Can you reproduce this with every photos ? Or a certain type (big sizes for example) ?

**Comment by cdujeu** [comment]
this should have been fixed in previous releases, please re-open if required
