### ISSUE TITLE
Cannot connect via android app

### ISSUE THREAD

**Issue by johanneskoester** [pydio/cells#217]
I use the docker-compose setup, and can properly access pydio via the web interface at https://<local-ip>:8080. However, when trying to connect via the android app, the following happens:

1. I am asked to accept the certificate, which is fine (self-signed as generated by the container itself).
2. Then it says, that the certificate cannot be checked. However, I can still hit "connect".
3. This brings me to the login screen. When entering username and password as they work fine on the web interface, I receive an error "Connection with server failed.".

**Comment by willipreuk** [comment]
I have the same error. :/

**Comment by cdujeu** [comment]
@jabarkarim can you have a look at this?

**Comment by willipreuk** [comment]
The logs show, that the authentication is successful but nothing happens in the app.

**Comment by jabarkarim** [comment]
Hello,

I would like to access to your server using my device in order to understand the cause of the problems you are encountering.

Is it possible that you create a test user for me on your server.  You can send me the user info at jabar@pydio.com

**Comment by CatSama-D** [comment]
same problem

**Comment by DjZU** [comment]
Hello, same problem here as well: the Android app says the certificate cannot be verified, it still shows and I can accept it but after it says the connection to the server failed. 
Any clue or workaround much appreciated.

**Comment by DjZU** [comment]
Found out that full certification is required for the Android app.
Solved by concatenating the certificate for my domain with the intermediate one.
When testing with a self-signed certificate, I guess importing the rootCA to your Android will make it.

**Comment by cdujeu** [comment]
closing, please use the Forum for config / apps issues
