### ISSUE TITLE
[Bug] Error "could not unmarshall response with status 404" at login

### ISSUE THREAD

**Issue by KaKi87** [pydio/cells#224]
**Log entry :**
```
ERROR   pydio.rest.frontend     Rest Error 401  {"error": "could not unmarshall response with status 404: 404 Not Found\nerror cause: invalid character '<' looking for beginning of value"}
```

**Environment :** Debian 10, MySQL 8.0.19, Cells v2.0.6

**Screenshot :**

![2020-04-24 11_25_41-Pydio Cells and 18 more pages - Personal - Microsoft_ Edge-min](https://user-images.githubusercontent.com/21284089/80197112-7e0acf80-861e-11ea-9f1e-5dba12623eb9.png)

Thanks

**Comment by cdujeu** [comment]
Please post on the forum https://forum.pydio.com thx

**Comment by KaKi87** [comment]
Done... But, why ?
Yet another account to create, manual validation, repost...

**Comment by cdujeu** [comment]
thanks for the effort
Because we are a small team, because most problems are not "bugs" but just configs issues until they are properly qualified as bugs.

**Comment by KaKi87** [comment]
Well, I can give you a real one : CLI installer doesn't prevent uppercase in username while GUI one does. (It didn't fixed my issue though).

**Comment by cdujeu** [comment]
:-) Be my guest => open an issue for that! 
Can't see your post in the forum, can you send me the link?

**Comment by KaKi87** [comment]
> :-) Be my guest => open an issue for that!

Done.

> Can't see your post in the forum, can you send me the link?

Here it is : https://forum.pydio.com/t/bug-error-could-not-unmarshall-response-with-status-404-at-login-224/3226

Thanks

**Comment by KaKi87** [comment]
Hello, I have no news on my issue on the forum ? Thanks
