### ISSUE TITLE
Feature Request: implement house keeping

### ISSUE THREAD

**Issue by fajo-de** [pydio/cells#236]
Certain files are growing endlessly. This are mainly logs (text or boltdb based). There should be brought some housekeeping inplace to limit the storage used by these files. Ideally, the limits should be made configurable.

I identified the below file locations that will need to have housekeeping in place:

```
.config/pydio/cells/logs/
.config/pydio/cells/services/pydio.grpc.log/syslog.bleve/
.config/pydio/cells/services/pydio.grpc.jobs/tasklogs.bleve/
```

While the text based log files in logs/ can be reset by truncating them it is required for the .bleve folders to stop Cells and remove the complete .bleve folder. After restarting Cells the folder will be re-created with a fresh bolddb in place. Here, housekeeping should be able to clean the database and index without having to stop Cells.

Thanks,
Falk

**Comment by cdujeu** [comment]
Added sharding on bleve logs, should be made easier, will be documented in next version

**Comment by cdujeu** [comment]
Starting with Cells **2.1.5**, syslog.bleve/ is now automatically rotated, creating sharded indexes with ~200MB size each. 

They appear as 
- syslog.bleve
- syslog.bleve.0001
- syslog.bleve.0002
- syslog.bleve.0003
- ... 
- syslog.bleve.000N

where syslog.bleve.000N is the **more recent** one containing logs.

At upgrade, you can trigger logs reconstruction (and thus splitting huge existing syslog.bleve folder into smaller ones) by launching `./cells data sync --service pydio.grpc.logs`

Cleaning logs starting from oldest ones can be done afterward by launching `./cells data sync --service pydio.grpc.logs --path=truncate/{{maxsizeinbytes}}` or also by stopping service, removing oldest ones e.g. syslog.bleve, syslog.bleve.0001, syslog.bleve.0002, and then at restart the remaining ones will be automatically renumbered.

Finally, the 200MB value can be fine-tuned inside pydio.json configuration file by setting services/pydio.grpc.log/bleveRotationSize configuration value.
