### ISSUE TITLE
viper.go:1613:2: undefined: io.StringWriter

### ISSUE THREAD

**Issue by MaliahRajan** [pydio/cells#240]
go get -u github.com/pydio/cells

# github.com/pydio/cells/vendor/github.com/ory/viper
../ubuntu/go/src/github.com/pydio/cells/vendor/github.com/ory/viper/viper.go:1613:2: undefined: io.StringWriter

**Comment by cdujeu** [comment]
cannot reproduce that
Please provide more info
 - go version? 
 - GOPATH set?
