### ISSUE TITLE
[Improvement] Automatic installation process

### ISSUE THREAD

**Issue by v-byte-cpu** [pydio/cells#245]
Right now it is necessary to configure database parameters (url, db, user, pass) manually during installation process. It would be great to setup every parameter in configuration file or in env variables like in [gitea](https://github.com/go-gitea/gitea):
https://docs.gitea.io/en-us/install-with-docker/

**Comment by cdujeu** [comment]
duplicate of #199 - @bsinou will add some indications about the --yaml parameters in this issue
