### ISSUE TITLE
initial setup loop on "installation finished, starting all services"

### ISSUE THREAD

**Issue by mezoology** [pydio/cells#246]
I'm using portainer.. when checking the container log I see a loop of this block

```
https://pastebin.com/8mp8n2Hm
```

**Comment by drzraf** [comment]
Possibly related: https://forum.pydio.com/t/failed-to-initialize-oidc-server-server-no-connectors-specified/3101/5 ?

**Comment by cdujeu** [comment]
Please use the forum for non-qualified issues
