### ISSUE TITLE
auto update fails on windows

### ISSUE THREAD

**Issue by gitzec** [pydio/cells#254]
cells 2.1.3 tries to rename itself to "cells.exe-rev-2020-07-29T15:53:14.exe"...
webclient: "rename C:\Services\Cells\cells.exe C:\Services\Cells\cells.exe-rev-2020-07-29T15:53:14: Falscher Parameter."

windows dows not allow ":" in filenames, so this fails.

workaround: delete old cells.exe and rename ".cells.exe.new" to "cells.exe"

**Comment by bsinou** [comment]
Hello, 

thanks for reporting. 
We have fixed this in the main branch and it will be included in the next version (2.1.5).
That is: you will have to manually update one more time and it will then run smoothly.
