### ISSUE TITLE
Can not search a name of file/folder which is in CJK(Chinese/Japenese/Korean)

### ISSUE THREAD

**Issue by listeng** [pydio/cells#255]
Can not search a name of file/folder which is in CJK(Chinese/Japenese/Korean). There are nothing found when input a CJK string in search input control. But I try to modify the func createIndex() in "data/search/dao/bleve/bleve.go", add:

`
pathFieldMapping2 := bleve.NewTextFieldMapping()

pathFieldMapping2.Analyzer = "keyword"

nodeMapping.AddFieldMappingsAt("Basename", pathFieldMapping2)
`

After that, remove index file in "searchengine.bleve" folder and recreate it. The CJK string can be searched. Are there any disadvantage of add mapping for Basename? Thanks.

**Comment by cdujeu** [comment]
Hi @listeng 

Thanks for posting!

Unfortunately I think it's not that simple. Using the "keyword" analyzer will only search on basenames "as a whole", which means that for example (for english) a search on "azer*" will not find file named "azerty"... Where as the default analyzer (Standard) is good for searching with wildchards.

Dedicated analyzers for bigram-based languages (like chinese or japanese) should be a better way to go, we are checking on how to implement this.

We'll keep you posted
Charles

**Comment by cdujeu** [comment]
I just commited something :-) 
Can you try to build on latest master, and add "basenameAnalyzer":"cjk" inside the pydio.json under the pydio.grpc.search service configuration? Then resync the search service to recreate index. Please tell me if it's working. If you have chinese examples to test it would be cool as well.
Charles

**Comment by listeng** [comment]
Great work! I add "basenameAnalyzer":"cjk" to pydio.json and restart Cells. After run command "./cells data sync --service=pydio.grpc.search", it worked. Thanks.

**Comment by cdujeu** [comment]
Cool, it will be in the next release

**Comment by cdujeu** [comment]
fixed in 2.1.5
