### ISSUE TITLE
MySQL TLS Support

### ISSUE THREAD

**Issue by nick-oconnor** [pydio/cells#263]
Cells does not currently appear to support validating MySQL TLS certificates or authenticating to MySQL databases with client certificates. Connecting to a TLS-only database is currently workable by passing `tls=skip-verify`, however the ability to construct and reference a `TLSConfig` would be a nice feature. For reference, I searched the codebase for [RegisterTLSConfig](https://godoc.org/github.com/go-sql-driver/mysql#RegisterTLSConfig) and didn't find anything.

**Comment by cdujeu** [comment]
Ready in v4
