### ISSUE TITLE
Swagger for Pydio V2

### ISSUE THREAD

**Issue by jahrralf** [pydio/cells#265]
How can we get the swagger definition file for Pydio cells v2? Is there one? Thanks.

**Comment by cdujeu** [comment]
Here : https://app.swaggerhub.com/apis/pydio/pydio-core/2

**Comment by jahrralf** [comment]
And this is for pydio cells and not for pydio server? It says "description: Access to a Pydio Server. Second version of the API. Available since Pydio 7."

**Comment by jahrralf** [comment]
Maybe this one? https://app.swaggerhub.com/apis/pydio/pydiocells/2.0

**Comment by cdujeu** [comment]
Sorry I misread your first post .. Forget first link I thought you were looking for Pydio PHP.
Swagger is served through the api as you’ve seen in the other ticket, check the console to load it manually

**Comment by jahrralf** [comment]
OK, thanks for you assistance. I finally saw that all API queries are documented in the console. Did not know this... 

However, how can I access the swagger file for pydio cells? I'd like to generate a php client based on this (and we would need the securityDefinitions section, else the whole generation process is useless).

Thanks in advance, @cdujeu .

**Comment by bsinou** [comment]
The reference current swagger file for Pydio Cells is here:
https://raw.githubusercontent.com/pydio/cells/master/common/proto/rest/rest.swagger.json
