### ISSUE TITLE
Swagger for Cells v2 / Security

### ISSUE THREAD

**Issue by jahrralf** [pydio/cells#266]
Next question, assuming that there is some endpoint which will provide this: https://github.com/pydio/cells/blob/master/common/proto/rest/swagger.go

Why is there no securityDefinitions section in this file? Is this added by cells before rendering it?

**Comment by cdujeu** [comment]
Indeed

**Comment by jahrralf** [comment]
So this means that the swagger definition is incomplete and we cannot use it it do generate a client?

**Comment by cdujeu** [comment]
look at common/config/rest/api-discovery.go - it's pretty straightforward to add your own security section
Or grab it from https://your-cells-instance/a/config/discovery/openapi and use it directly

**Comment by jahrralf** [comment]
@cdujeu , thanks for finally showing us the URL were we can get the full swagger file. Is this mentioned somewhere in the documentation?

In the meantime we added our own security section, we will see which one we are going to use in the end.

**Comment by cdujeu** [comment]
sorry I thought you had it already :-)
