### ISSUE TITLE
Support for native ftp over ssh plugin like Pydio 8

### ISSUE THREAD

**Issue by superguillen** [pydio/cells#267]
We need migrate from pydio 8 to cells, and not found the plugin for ssh

**Comment by cdujeu** [comment]
hello - there will probably not be such a feature. Instead, you should mount the storage directly using sshfs and access it "locally" from Cells
Charles

**Comment by cdujeu** [comment]
Hello @superguillen  - Cells storage relies on s3 protocol (we deploy a local Min.io service to emulate that on local fs), so there is no easy way to that....
