### ISSUE TITLE
Cell v2 on web server not accessible from the outside

### ISSUE THREAD

**Issue by BenJule** [pydio/cells#273]
Pydio Version: linux-arm64
Debian Version: latest Buster

The server can be reached internally -> https://192.168.1.12:8080
But when I get from my domain https://pydio.s3root.ovh I get an error 522
I have try following settings:

sudo setcap ‘cap_net_bind_service=+ep’ /home/benlue/cells

internal: 0.0.0.0:8080 external: https://pydio.s3root.ovh with & without selfsigned ssl
internal: 192.168.1.12:8080 external: http://pydio.s3root.ovh with & without selfsigned ssl

Cloudflare: DNS SNI SSL ON&OFF

with & without /etc/apache2/sites-available/pydio.s3root.ovh.conf
https://hastebin.s3root.ovh/sevirolede.apache

**Comment by cdujeu** [comment]
if not already, please use the [Forum](https://forum.pydio.com) for such config/network questions
