### ISSUE TITLE
[File preview] Add nbviewer for .ipynb files

### ISSUE THREAD

**Issue by marioreggiori** [pydio/cells#277]
Would it be possible to add a viewer for [.ipynb](https://en.wikipedia.org/wiki/Project_Jupyter#Jupyter_Notebook) files?
Jupyter has an official notebook viewer, which could be displayed via iframe.
Working example using Github Gist as file host: [nbviewer](https://nbviewer.jupyter.org/urls/gist.githubusercontent.com/marioreggiori/c9d8cf0e32e28a960b64cf1fe3731b37/raw/024e9e7fadc1a1d7dab5f4deaf9535eb6f3a376e/Hello%2520World.ipynb) from [gist](https://gist.githubusercontent.com/marioreggiori/c9d8cf0e32e28a960b64cf1fe3731b37/raw/024e9e7fadc1a1d7dab5f4deaf9535eb6f3a376e/Hello%2520World.ipynb).

URL format for iframe:
https://nbviewer.jupyter.org/urls/pydio.example.com/io/some/path/to.ipynb?access_token=some_token

**Comment by cdujeu** [comment]
Hello mario, this could be interesting. We would have to create a new editor on the JS side. 
Any chance to have you contribute ? Do you have experience with npm / grunt / reactJS ?

**Comment by marioreggiori** [comment]
Hello Charles, I do not have any experience with grunt. But I think I will be able to figure it out. I will get back to you as soon as I have implemented the viewer.

**Comment by cdujeu** [comment]
Cool, do not hesitate to ask for some guidelines for adding an "editor.*" JS plugin

**Comment by marioreggiori** [comment]
I've managed to add the the plugin.
Since english isn't my primary language, the text may need to be revised.
I'd be happy about some feedback.

This is how it looks like in the file explorer:

![](https://gist.github.com/marioreggiori/138f14d6453119001ff907ec85131b9a/raw/fa3feb60f3d0a5d7e00265ab6d8195becaf3350c/1.PNG)

When opened:

![](https://gist.github.com/marioreggiori/138f14d6453119001ff907ec85131b9a/raw/fa3feb60f3d0a5d7e00265ab6d8195becaf3350c/2.PNG)

I also added an option in the plugin settings to prevent people from accidentally sharing private information with [nbviewer.jupyter.org](https://nbviewer.jupyter.org/) (disabled by default)

![](https://gist.github.com/marioreggiori/138f14d6453119001ff907ec85131b9a/raw/fa3feb60f3d0a5d7e00265ab6d8195becaf3350c/3.PNG)

File explorer with **Preview without consent** option disabled:

![](https://gist.github.com/marioreggiori/138f14d6453119001ff907ec85131b9a/raw/fa3feb60f3d0a5d7e00265ab6d8195becaf3350c/4.PNG)

Viewer with **Preview without consent** option disabled:

![](https://gist.github.com/marioreggiori/138f14d6453119001ff907ec85131b9a/raw/fa3feb60f3d0a5d7e00265ab6d8195becaf3350c/5.PNG)

**Comment by cdujeu** [comment]
Great job mario ! 
Would you send a pull request? We can review the code an integrate it!

**Comment by cdujeu** [comment]
Closing as solved by OP.
