### ISSUE TITLE
[BUG] Add LocalName parameter on SMTP mailer

### ISSUE THREAD

**Issue by mzch** [pydio/cells#279]
When selecting SMTP server, Cells can't send a mail, because Cells send `localhost` in `EHLO` command, some mail servers reject non-FQDN helo server name. Please add `Dialer.LocalName` in `pydio.json` and use it.

**Comment by cdujeu** [comment]
Hi @mzch thanks for pointing out!

**Comment by cdujeu** [comment]
@mzch if you can test, i've pushed the change in the code. 
(Make sure to test with a proper clean install as the current master introduces non-revertible changes with 2.1.X)

**Comment by mzch** [comment]
Great! Cells has sent an email successfully. Thanks!

**Comment by mzch** [comment]
But, the latest code listens on only :8080 and protocol is https. It's not selectable. I want to select internal url and external url separately.

**Comment by cdujeu** [comment]
Use the new command `./cells config sites` :-) You will see the whole new stuff!

**Comment by mzch** [comment]
Thanks! And on more question.
I started cells manually and visited my site...OK. Cells works well, but I started cells using systemd, I encountered `404 Not found`.
Please give me hints to fix this.

```systemd
[Unit]
Description=Pydio Cells
Requires=network.target
After=network.target

[Service]
Type=simple
User=cells
Environment=CELLS_WORKING_DIR=/srv/cells/cells
LimitNOFILE=65536
WorkingDirectory=/srv/cells/.go/src/github.com/pydio/cells
ExecStart=/srv/cells/.go/src/github.com/pydio/cells/cells start

[Install]
WantedBy=multi-user.target
```

**Comment by mzch** [comment]
Oh, I added `Environment=GOPATH=/srv/cells/.go`, systemd starts cells successfully.
Is there any ways to create standalone binary? If exists, please tell me it.

**Comment by cdujeu** [comment]
You should probably wait for the final binary to be ready. 
Otherwise you have to install packr (go get github.com/pydio/packr) and run `make generate` before building your own binary.
-c

**Comment by mzch** [comment]
Mm..? I did `go get github.com/pydio/packr` and `make all`, but cells needs `GOPATH` env variable...?
Anyway I'm going to wait for a new release. Thanks! :)
