### ISSUE TITLE
Unable to build with go 1.11

### ISSUE THREAD

**Issue by max-k** [pydio/cells#29]
Here is the output of make dev using go 1.11.1:
```.bash
go build\
 -ldflags "-X github.com/pydio/cells/common.version=0.2.0\
 -X github.com/pydio/cells/common.BuildStamp=2018-01-01T00:00:00\
 -X github.com/pydio/cells/common.BuildRevision=dev"\
 -o cells\
 main.go
# command-line-arguments
github.com/pydio/cells/vendor/golang.org/x/crypto/blake2b.supportsAVX2: relocation target runtime.support_avx2 not defined
github.com/pydio/cells/vendor/golang.org/x/crypto/blake2b.supportsAVX: relocation target runtime.support_avx not defined
make: *** [Makefile:49: dev] Error 2
```
It works perfectly with go 1.10.3.

Maybe this issue could help: https://github.com/golang/go/issues/25098.

**Comment by Yamilquery** [comment]
Yes. It also can not be installed using version 1.11.2 

```
go build\
         -tags dev\
         -ldflags "-X github.com/pydio/cells/common.version=0.2.0\
         -X github.com/pydio/cells/common.BuildStamp=2018-01-01T00:00:00\
         -X github.com/pydio/cells/common.BuildRevision=dev"\
         -o cells\
         .
# github.com/pydio/cells/vendor/github.com/rjeczalik/notify
vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:51:216: cannot use nil as type _Ctype_CFAllocatorRef in argument to func literal
vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:165:47: cannot use nil as type _Ctype_CFAllocatorRef in argument to _Cfunc_CFStringCreateWithCStringNoCopy
vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:166:225: cannot use nil as type _Ctype_CFAllocatorRef in argument to func literal
make: *** [dev] Error 2
```

**Comment by Yamilquery** [comment]
Even I tried with `go version go1.10.5 darwin/amd64` and I get this error:

```
go build\
         -tags dev\
         -ldflags "-X github.com/pydio/cells/common.version=0.2.0\
         -X github.com/pydio/cells/common.BuildStamp=2018-01-01T00:00:00\
         -X github.com/pydio/cells/common.BuildRevision=dev"\
         -o cells\
         .
# github.com/pydio/cells/vendor/github.com/rjeczalik/notify
vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:51: cannot use nil as type _Ctype_CFAllocatorRef in argument to func literal
vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:165: cannot use nil as type _Ctype_CFAllocatorRef in argument to _Cfunc_CFStringCreateWithCStringNoCopy
vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:166: cannot use nil as type _Ctype_CFAllocatorRef in argument to func literal
make: *** [dev] Error 2
```

**Comment by Yamilquery** [comment]
In this [Issue](https://github.com/golang/go/issues/23317) they suggest me to execute the following command to convert `nil` to `0`:

`go tool fix -r cftype ./`

However it doesn't work for me.

This is what I get:

```
➜  cells git:(master) go tool fix -r cftype ./
warning: no cgo types: exit status 1
warning: no cgo types: exit status 1
warning: no cgo types: exit status 1
warning: no cgo types: exit status 1
➜  cells git:(master) go test
# github.com/pydio/cells/vendor/github.com/rjeczalik/notify
vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:51:216: cannot use nil as type _Ctype_CFAllocatorRef in argument to func literal
vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:165:47: cannot use nil as type _Ctype_CFAllocatorRef in argument to _Cfunc_CFStringCreateWithCStringNoCopy
vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:166:225: cannot use nil as type _Ctype_CFAllocatorRef in argument to func literal
➜  cells git:(master)
```

**Comment by cdujeu** [comment]
@bsinou can you check this ticket please?

**Comment by bsinou** [comment]
Hello, 

I have quickly tested the different versions for linux/amd64 on CentOS 7.
We definitively have the issue reported by @max-k as from version 1.11.

But build and tests pass with all go version of the 1.10 branch, including 1.10.5 released last Friday.
Thanks to the good work of @Yamilquery , we know that the problem (that is not related to the first one) comes from the `notify` TP library from rjeczalik and his specific to the latest version of MacOS. 
We will have a closer look and give feedback.

**Comment by mersinvald** [comment]
@max-k @bsinou are there any updates about how to fix this issue on Mac OS X Mojave?
We've encountered the same issue in `etheriumproject/go-etherium` and `go tool  fix -r cftype` does not work either.

**Comment by cdujeu** [comment]
hi guys
1/ notify issue is fixed in the master branch => build for 1.10.5
2/ The 1.11 issue is different (github.com/pydio/cells/vendor/golang.org/x/crypto/blake2b.supportsAVX2: relocation target runtime.support_avx2 not defined)
I did not check where it comes from yet
charles

**Comment by cdujeu** [comment]
and for notify => we had to update the notify lib in the vendor folder.

**Comment by max-k** [comment]
Hi,
I think you only have to update these dependencies:
* x/sys/cpu
* x/crypto/blake2b
They seem unused in your code, so perhaps you could simply remove them.

**Comment by cdujeu** [comment]
Actually I just retested : the master branch does build on 1.11 since we updated the minio-srv inside vendor! See https://travis-ci.org/pydio/cells/jobs/457886544

These dependencies are used by underlying libs (minio)

Can you try to pull the last version from master?

**Comment by cdujeu** [comment]
Building for Travis with go 1.11.2
