### ISSUE TITLE
Ability to manually regenerate thumbnails for a data source

### ISSUE THREAD

**Issue by wpuckering** [pydio/cells#302]
I'm not sure if this functionality already exists or not (I hunted around and could not find anything like this), but if a given data source contains images, and if for whatever reason thumbnails didn't generate properly for some of them, we should have a way to kick off a job that goes through all of the images in a data source that are missing thumbnails and attempt to regenerate them. Obviously for images that already have them, these can be skipped.

Is there already a way to do this? Seems like re-synchronizing a data source does not do this. And I've seen suggestions in various places recommending to move files out of a data source and back in to get it to work, but this seems absolutely silly. So if this doesn't already exist as a function that can be performed in some way already, I think we need this. Or if it's already available, how would one regenerate thumbnails then without having to move files in and out of a data source?

**Comment by GwynethLlewelyn** [comment]
Thanks for opening this issue; I was wondering the same myself when looking at the `thumbs` directory. It seems that there are thumbnails generated with two widths, 300 and 1024. The image name itself uses some sort of internal ID; if you can make any sense of it, I suppose you can create the thumbnails on your own (for instance, using `ImageMagick`or some similar graphics conversion library).

However, in my own case, I 'fixed' things by doing exactly what you saw recommended elsewhere: after re-configuring Cells again — i.e. removing the content of the database and deleting the `pydio.json` file, and then running `./cells configure [...]` Cells did indeed refresh _all_ thumbnails from scratch, while previously thumb regeneration didn't seem to start on its own.

Granted, this meant losing some of the configuration details (which is inevitable if you're re-configuring Cells from scratch...) but at least the thumbnail regeneration, once the configuration had been freshly minted and applied, did most certainly work.. even though it *did* take an insane amount of time to complete.

So I'm definitely in favour of having an extra option on the settings to allow thumbnail regeneration. It would even be useful if it's just a command-line option and/or just available via the REST API.

**Comment by cdujeu** [comment]
Closing as more recent one is now a duplicate ;-)

**Comment by GwynethLlewelyn** [comment]
See also #432
