### ISSUE TITLE
Unhide filename extensions

### ISSUE THREAD

**Issue by Ralph67Git** [pydio/cells#303]
Hello,
please add a configuration setting which allows to hide/unhide the filename extensions. Currently the extension is hidden unless you hover with the mouse.

Regards
Ralph

**Comment by cdujeu** [comment]
Added in an option in the display settings - will be in next release ;-)

**Comment by cdujeu** [comment]
Hi @Ralph67Git , glad to announce this option is available in the 2.2.3, just released!
