### ISSUE TITLE
Docker container does not include keyring

### ISSUE THREAD

**Issue by valmar** [pydio/cells#31]
The docker container does not include a keyring. It is then impossible to create and store an encryption key. This in turn prevents the user from using encryption!

**Comment by cdujeu** [comment]
Good sport, thanks @valmar 
we'll have a look at this

**Comment by valmar** [comment]
@cdujeu Thank you. Temporarily, I will create for myself a pydio cells docker image based on Ubuntu or Debian (if there is interest, I can share it, of course). I read in the documentation that on Linux the Gnome keyring is used. But of course, one will not need to install the full Gnome desktop, right? Do you know what are the minimal dependencies in Linux, please?

**Comment by KungFu-Kenny** [comment]
Hi,
if you wish to have the keyring on a headless environment such as ubuntu,
required packages : dbus-user-session, gnome-keyring

then launch the keyring with the following command
`gnome-keyring-daemon —unlock` (can be launched in the foreground with —foreground)
<input user password, there will be no indication for it but right after you used the command type it>
<ctrl+d>

**Comment by cdujeu** [comment]
fixed in last version : we made keyring optional

**Comment by valmar** [comment]
@cdujeu Thanks. One question: without the keyring, how is the key stored? Is it stored in plain text?

**Comment by cdujeu** [comment]
nope, there's a dedicated "vault" storage where data are encrypted with a master key generated at startup.
