### ISSUE TITLE
Delete this issue!

### ISSUE THREAD

**Issue by PontusTideman** [pydio/cells#310]
Delete this issue...

**Comment by PontusTideman** [comment]
This is what the developer console showing in Chrome!

<img width="673" alt="Screenshot 2021-03-17 at 15 15 28" src="https://user-images.githubusercontent.com/9256550/111481936-ba15ba00-8733-11eb-9234-e1f973415702.png">

**Comment by cdujeu** [comment]
Everything is fine?
