### ISSUE TITLE
Manually managed TLS certificates ignored post-setup

### ISSUE THREAD

**Issue by JosefWN** [pydio/cells#316]
I mounted a proper CA-signed TLS cert into the Pydio pod pre-setup. It worked just fine during the setup, but once Pydio restarted, it created its own self-signed cert and started using it instead of the one I supplied. Would have expected Pydio not to create a self-signed cert when it already has a cert to use?

**Comment by piccobit** [comment]
I've exactly noticed the same problem.

**Comment by cdujeu** [comment]
See #391
