### ISSUE TITLE
Loading UploaderView :  TypeError: store.isRunning is not a function

### ISSUE THREAD

**Issue by Yamilquery** [pydio/cells#32]
I was configuring a storage with S3, however when I trying to load a file from the GUI I get this error:

<img width="1001" alt="screen shot 2018-11-14 at 12 53 01" src="https://user-images.githubusercontent.com/6020065/48505299-5221d280-e80c-11e8-9a37-f9902959da26.png">

**Comment by Yamilquery** [comment]
I did checkout to the v1.2.1 however I still getting the same error:

<img width="1440" alt="screen shot 2018-11-14 at 13 47 17" src="https://user-images.githubusercontent.com/6020065/48508322-e479a480-e813-11e8-8a35-1915da4f9734.png">

I'm not sure if it has to do with the storage AWS S3 that I configured.

**Comment by cdujeu** [comment]
did you clear your browser cache? it's only on an s3 storage?

**Comment by cdujeu** [comment]
closing as probably a cache issue
