### ISSUE TITLE
Please update github.com/jaytaylor/go-hostsfile to the latest version

### ISSUE THREAD

**Issue by skozlov404** [pydio/cells#324]
Latest version has an commit fixing build on FreeBSD:
https://github.com/jaytaylor/go-hostsfile/commit/f581673a59cf19f7ac16c2321791849aaa3b0998

**Comment by cdujeu** [comment]
Unfortunately, that latest version breaks windows build. 
We would have to send a PR to set the proper `// +build` instructions
