### ISSUE TITLE
`nil pointer dereference` when shutting down cells

### ISSUE THREAD

**Issue by skozlov404** [pydio/cells#325]
It seems like the logic in the code below is wrong. When `(process == nil || len(process.Services) == 0)`, but at the same time `len(childrenProcesses) != 0` - the code doesn't `return nil`, but instead continuing to `log.Info`, where `process == nil` is deferenced. 

https://github.com/pydio/cells/blob/e36a2541ce65a95d50719a5542be16c2cf6320bd/cmd/start.go#L288-L292

**Comment by cdujeu** [comment]
Hi @skozlov404 , thanks for reporting. @ghecquet can you have a look?
