### ISSUE TITLE
Connection problem when creating new folders or importing files

### ISSUE THREAD

**Issue by Adrienbjx** [pydio/cells#329]
![issue](https://user-images.githubusercontent.com/86350056/123071071-64813580-d425-11eb-9153-5cdfb79f3485.jpg)

Hello,

Whenever I create a folder, or import a file, nothing happens. I just get a brief error notification in the corner sometimes. If I click on it, it goes away quickly. 

Also, for some reason, I can still create empty files.

**Comment by cdujeu** [comment]
Hello Adrian
Please post support issues in the forum instead of github, thanks ! https://forum.pydio.com
-c
