### ISSUE TITLE
Cannot build on linux/i686 (32bits)

### ISSUE THREAD

**Issue by arnoo** [pydio/cells#33]
On master and 1.2.1, I get this error in the "go build" step when I try to build using "make":

`vendor/github.com/pydio/minio-srv/vendor/google.golang.org/api/transport/http/dial.go:30:2: no buildable Go source files in /home/pydio/.go/src/github.com/pydio/cells/vendor/github.com/pydio/minio-srv/vendor/google.golang.org/api/transport/http/internal/propagation
Makefile:39: recipe for target 'main' failed
make: *** [main] Error 1`

**Comment by cdujeu** [comment]
can you try with a more recent version of go ?

**Comment by arnoo** [comment]
I used go 1.7.4 because it is the version that is on Debian stable. 

After trying with go 1.11.2, and now stumble on another error : 

`# github.com/pydio/cells/vendor/github.com/micro/go-plugins/server/grpc
vendor/github.com/micro/go-plugins/server/grpc/util.go:139:12: constant 4294967295 overflows int`

bumping micro/go-plugins to the current master gives me other errors still...

**Comment by cdujeu** [comment]
Hello @arnoo - See https://travis-ci.org/pydio/cells/builds/460331572
The build is passing when starting from scratch with go1.11.2 ...

**Comment by arnoo** [comment]
Sure, but I'm trying to build on 32bits, which I guess is the issue. Certainly in the case of the integer overflow. Even if the title says "i686", I should have made clearer that 32bit was most likely the issue.

**Comment by cdujeu** [comment]
mm, yes sorry, I did not spot that. not sure where to go from there

**Comment by ghecquet** [comment]
It seems to be an issue in the micro library that has been resolved since. The obvious fix would be to upgrade the version but as you spotted it is not straightforward.

So fo now, we're not able to produce a 32 bits version

**Comment by cdujeu** [comment]
finally, the `main` branch can now be built for 32bits.
