### ISSUE TITLE
connect to the database without using IP address

### ISSUE THREAD

**Issue by wiebereu** [pydio/cells#330]
I run Pydio in Kubernetes. In the setting of the application i have to fill in the user, password and IP address of the database. The problem is that in an Kubernetes environment Pods restarted often and therefore the IP address change all the time. 
That is a problem with Pydio cause if the IP address of the database change i can't start the application. Is there a way to address this issue? I run Kubernetes in a cluster. and i use Pydio Cells latest version

**Comment by cdujeu** [comment]
Hello @wiebereu, thanks for posting!
 
Could you kindly post in the [forum](https://forum.pydio.com) for configurations questions? We will open a github issue only for "qualified" issues.

Thank you
