### ISSUE TITLE
Incorrect tag used 

### ISSUE THREAD

**Issue by albert-github** [pydio/cells#332]
In the file frontend/front-srv/assets/editor.ckeditor/res/dist/ckeditor/README.md on line 66 a couple of thimes the HTML tag `</br>` is used, but this tag does not exist one should use `<br>` (or `<br/>`)

**Comment by cdujeu** [comment]
this is an external library packaged, and this readme is not even used in the code... wontfix

**Comment by albert-github** [comment]
Understandable, I found the GitHub page of ckeditor (https://github.com/ckeditor) but I could not find the mentioned README.md as used by you. Do you perhaps a link to it so I can report the problem there?
