### ISSUE TITLE
tagging files dont persist, when ...

### ISSUE THREAD

**Issue by oliver68** [pydio/cells#333]
user is 'external' and permission to folder is 'readonly'.

Error message pops up and looks like set in UI but is not persisted.

**Comment by cdujeu** [comment]
hi it is in fact expected that readonly users cannot edit meta.
In the next version (currently master), the meta UI correctly reflects this.

**Comment by oliver68** [comment]
hi so 
will it be possible to add tags then cause comments can already be added or
will the button to edit metadata be grayed out?
whats the solution?

**Comment by cdujeu** [comment]
Metadata panel stays readonly (not a form anymore)

**Comment by oliver68** [comment]
Thx for information
