### ISSUE TITLE
Activities on folders and files (german translation)

### ISSUE THREAD

**Issue by oliver68** [pydio/cells#334]
when i see entries for myself on activities they are right now called 'Ihnen'!

this is not correct. u can say 'Du' or 'Sie'.

'Du': is used when ur talking to a person u know better (not so formal)
'Sie': is used when u dont know someone or ur in formal relationship to this person

U have to decide in general for german translation for the formal or the more personal way?

**Comment by bsinou** [comment]
Hello @oliver68, thanks for the feedback. 

For the german translation, we use the formal form (Sie).

Thus said, you are more than welcome to directly suggest corrections when/if you spot any mistake or typo: we use crowdin to easily manage the internationalization of the GUI.

Would you mind to create an account and directly correct the messages that are not OK? 

https://crowdin.com/project/pydio-cells 

Many thanks in advance.
