### ISSUE TITLE
Add armv8 support

### ISSUE THREAD

**Issue by pi-dal** [pydio/cells#336]
Hey！
I wanted to use docker to deploy pydio on raspberry pi, but I was surprised to find that the docker image of pydio did not have the armv8 version, which made me a little confused. I read the issue(#191).I found that others also have such needs. I would like to ask when the armv8 image can appear. Because I'm really in a hurry (I'm still a student and don't have much spare time)! thank you 🙏

**Comment by bsinou** [comment]
Hello, 

we still haven't taken the time to add the docker image for ARM on the hub, but you might quite simply build one yourself by _forking_ the AMD docker file from our repo [1] and using the ARM build [2].

Thus said, we would rather prefer that you use our forum [3] for such request. thanks in advance 

[1]: https://github.com/pydio/cells/tree/master/tools/docker/images/cells
[2]: https://download.pydio.com/pub/cells/dev/linux-arm64/cells
[3]: https://forum.pydio.com/

**Comment by pi-dal** [comment]
Thank you for your suggestion, I think I should go back to practice it!
