### ISSUE TITLE
this authentication plugin is not supported on MacOS Mojave

### ISSUE THREAD

**Issue by IanPhilips** [pydio/cells#34]
On MacOS Mojave using go version 1.11 following installation instructions except the `./deps.sh` if I run `./cells install` and use the browser installer I get  
<img width="883" alt="screen shot 2018-11-26 at 1 17 23 pm" src="https://user-images.githubusercontent.com/23196210/49039751-e2053c00-f17d-11e8-80e3-cba3a4a61b3f.png">

and with the command line installer I get :
`2018-11-26T13:16:19.614-0700	FATAL	Cannot connect to this database, please double ckeck your connection parameters and try again.`

I have mySQL version: `Server version: 8.0.12 Homebrew` and it is running on port 3306 using root user without a password. Any ideas what's going on?

**Comment by KungFu-Kenny** [comment]
Hi,
this error is occuring because MySQL 8 has a new authentication method, at the moment you should use mysql 5.7 or mariadB 11.3.

It is on our roadmap and we will soon support the MySQL 8 new authentication method.

**Comment by IanPhilips** [comment]
gotcha, thanks for the tip.
