### ISSUE TITLE
Update vendor/golang.org/x/sys/unix please

### ISSUE THREAD

**Issue by MikaelUrankar** [pydio/cells#347]
it's 3 years old now :(

**Comment by MikaelUrankar** [comment]
and vendor/golang.org/x/net and vendor/github.com/pydio/minio-srv/vendor/golang.org/x/

**Comment by cdujeu** [comment]
that's totally right - but our main goal would be to move to modules... upgrading the vendor may very probably be a breaking change for now....

**Comment by cdujeu** [comment]
Not officially release yet, but the `main` branch now uses modules.
