### ISSUE TITLE
Switching Pydio Cells v3 branch to v2 branch, files do not appear anymore

### ISSUE THREAD

**Issue by BamBoozledMC** [pydio/cells#359]
I've just updated my Pydio Cells to the latest version and now all my files are gone.
All the files are still located on the drive however i'm unable to identify what is what since they are all encrypted into random strings

Please help i dont have a backup D:
![pydio1](https://user-images.githubusercontent.com/64771089/135440180-ac82bb49-26bc-4cce-a6e1-9e81b162430c.PNG)
![pydio2](https://user-images.githubusercontent.com/64771089/135440212-0fa7b138-8dbf-4c80-b889-1c02046b1423.PNG)

**Comment by BamBoozledMC** [comment]
![image](https://user-images.githubusercontent.com/64771089/135440314-735151a9-2363-4c8b-a00a-930e49996e0c.png)

Somehow it still has my file history

**Comment by cdujeu** [comment]
hello
can you specify the from / to versions before and after upgrade ?

**Comment by BamBoozledMC** [comment]
> hello can you specify the from / to versions before and after upgrade ?

Somehow i was using the oldest version (0.1.0) and i updated to 2.2.12

**Comment by cdujeu** [comment]
0.1.0 ???

**Comment by BamBoozledMC** [comment]
> 0.1.0 ???

according to the renamed file- yea,
i originally downloaded the repository to edit some code to change a few things

**Comment by BamBoozledMC** [comment]
i can upload the binary file i compiled if thats any help

**Comment by cdujeu** [comment]
ah - ok so you built it in dev mode, you are working on the master which is not stable, the 2.2.12 is not on the same branch, and the default datasource format in the master is different from 2.2.X branch.  
=> go back to master by using v3-rc1 binary, you should be back on tracks.

**Comment by BamBoozledMC** [comment]
where can i find the v3-rc1 binary?

**Comment by cdujeu** [comment]
you can even use rc2, it's in pre-release mode but still usable
https://download.pydio.com/pub/cells/release/3.0.0-rc2/

**Comment by cdujeu** [comment]
(or if you have the code (master branch), you can just rebuilt it after updating it from git, it will be more ore less the same)

**Comment by cdujeu** [comment]
Next time please use the FORUM instead of github, thanks.

**Comment by cdujeu** [comment]
And please read https://github.com/pydio/cells/releases/tag/v3.0.0-rc1 to understand what you are doing ;-)

**Comment by BamBoozledMC** [comment]
Alright!

After downloading the binary from https://download.pydio.com/pub/cells/release/3.0.0-rc2/

All my files are still missing

**Comment by cdujeu** [comment]
do you have a backup of your DB ?

**Comment by BamBoozledMC** [comment]
> do you have a backup of your DB ?

Possibly but it is outdated and will not include alot of recently added files

**Comment by cdujeu** [comment]
They are not encrypted, they are just stored by uuid (see the link in the release note) instead of their name... 
I think you are screwed, you were not supposed to switch branch between master ( = dev) and stable.

**Comment by BamBoozledMC** [comment]
> They are not encrypted, they are just stored by uuid (see the link in the release note) instead of their name... I think you are screwed, you were not supposed to switch branch between master ( = dev) and stable.

frick.

Where would the indexes for the files be located?

**Comment by cdujeu** [comment]
in the DB

**Comment by BamBoozledMC** [comment]
> in the DB

Which one the physical db (where all the files are) or the mysql db

**Comment by cdujeu** [comment]
mysql

**Comment by BamBoozledMC** [comment]
well that makes it harder to restore :/

**Comment by cdujeu** [comment]
please read https://github.com/pydio/pydio-doc-admin-guide/blob/cells-v3/4_connecting_your_storage/1_datasource_format.md to understand better

**Comment by BamBoozledMC** [comment]
Oh well, i'll see what i can do, but for now thanks for your help :)

**Comment by cdujeu** [comment]
🔝  and this link shows how this new datasource format should be backup / restored

**Comment by cdujeu** [comment]
(but you switched back a "flat" DS to "structured" DS, which in turn probably triggered an indexation of the original DS and cleared the DB index...)

**Comment by cdujeu** [comment]
closing as it's not really an issue
