### ISSUE TITLE
Create a switchable theme: light/dark.

### ISSUE THREAD

**Issue by filhocf** [pydio/cells#360]
Some users (in a growing vision) prefers dark themes. In systems where offers dark themes I always switch for this option because is more confortable for me. A example for this is here, at Github, for example. You can set it to a dark theme. 

It is my suggestion: only create a switchable theme: light/dark, like Github

**Comment by cdujeu** [comment]
at one point we'll update material-ui ... and light/dark will be ready out-of-the-box :-). Until then... a bit overkill

**Comment by GwynethLlewelyn** [comment]
Just to add my voice to those who would _love_ to get a dark theme :-)

**Comment by naami2004** [comment]
The same here, dark theme will be a good addition

**Comment by cdujeu** [comment]
fyi, a massive dev is in progress in the @mui3 branch, including Dark/Light theme ! if anyone wants to have a go... a build can be found in https://download.pydio.com/pub/cells/dev/next/linux-amd64/ 
no upgrade tests were done yet...

**Comment by cdujeu** [comment]
Closing as this has been implemented in v4.2.
