### ISSUE TITLE
[Bug] Mobile page, duplicate options 'Size' in 'Sort by...'

### ISSUE THREAD

**Issue by callmelex** [pydio/cells#369]
Duplicate options 'Size' in 'Sort by...', different option type but make no sense.
(switch desktop layout to mobile layout, works fine, **problem occurs after F5** )

![image](https://user-images.githubusercontent.com/11659851/140282628-46194520-b1cb-4761-a90d-05b1d31a7376.png)

**Comment by cdujeu** [comment]
(fixed in main branch)
