### ISSUE TITLE
Cannot start pydio. Getting bad connection

### ISSUE THREAD

**Issue by AlexTalavari** [pydio/cells#37]
I am trying to run pydio on an ubuntuon aws lightsail 

Following the documentation on the website my installation when running throws this error and my terminal hangs
`pydio.grpc.config       Could not run  {                                                                                                                                                             "error": "bad connection"}
`

**Comment by bsinou** [comment]
Please rather open a ticket in the forum: forum.pydio.com. (see also:  https://github.com/pydio/cells/blob/master/CONTRIBUTING.md#contributing-to-pydio-cells ) 

By the way,  the people there will certainly appreciate (I mean be able to help you...) more info about your set up: which version of Pydio, of ubuntu, which step you managed to reach, etc...

Closing this for now.
