### ISSUE TITLE
Wrong version in Pydio Cells Dashboard

### ISSUE THREAD

**Issue by jkirk** [pydio/cells#372]
Just updated to Pydio Cells Home Edition 3.0.1.

In Cells Console -> Software Update the version is shown correctly, but not the Dashboard itself shows "Welcome to Pydio Cells v2":

https://github.com/pydio/cells/blob/c2dcb57c20b3b6feba11e1043b3ec7f06b6b5f35/frontend/front-srv/assets/access.settings/res/i18n/dashboard/en-us.all.json#L96

(Note, other languages show the wrong version too.)

Also, it would be helpful if the version is shown in the About page. Thx.

**Comment by cdujeu** [comment]
Thanks @jkirk, fixed in v3.0.2
