### ISSUE TITLE
Joplin sync upload error WebDAV (Hidden files/folders)

### ISSUE THREAD

**Issue by nuxlight** [pydio/cells#377]
Hi,

For now many days, I tried Cells to replace my Seafile instance.
But I have a problem with Joplin synchronization (WebDAV) as you can see on my screenshot, I have DAV ERROR when Joplin try to make a PUT request.
![image](https://user-images.githubusercontent.com/2751135/143448367-3aa8da7b-d7be-448c-a408-bdd41048853d.png)
Have you ever see this issue ?

Thanks for your help !

**Comment by cdujeu** [comment]
Hi, can you try to run cells in debug mode (--log debug) and see if there is more info about the error ?

**Comment by nuxlight** [comment]
No, I tried just now, and I have this :
![image](https://user-images.githubusercontent.com/2751135/143589370-434748a3-f0f1-4704-b5ad-7e43925a598f.png)

**Comment by cdujeu** [comment]
hum, not very informative unfortunately ;-)
what is this /Joplin/.sync/version.txt file ? Is it a real file ? 0 bytes maybe ?

**Comment by nuxlight** [comment]
Yes you right, I will try to start cells in debug mod to check exactly what query of Joplin look like.
The file weight is only 1 :
 
![image](https://user-images.githubusercontent.com/2751135/143735231-de8b5e25-de7c-49fb-8dca-e880ab1329cd.png)

**Comment by nuxlight** [comment]
Just to look, I've opened the debugging window on Joplin to see all request during the synchronization,
As you can see, Joplin makes a PUT request with the version file and after some minutes, Cells gives this methods' error.
![image](https://user-images.githubusercontent.com/2751135/144204302-815ca74a-6115-47a5-bdf9-797ff864b08a.png)

**Comment by nuxlight** [comment]
Okay I add some logs on Cells it's confirmation that Cells doesn't accept hidden folders :(
![image](https://user-images.githubusercontent.com/2751135/144212476-7785453e-90e6-473c-ac0f-d3830fec54ce.png)
I see on the file **filesystem.go** this part of code that revoke all hidden creations.
![image](https://user-images.githubusercontent.com/2751135/144212874-a0a0242b-0960-43a4-bb28-a19d6a596314.png)
Do you think it's possible to add this possibility on your app ? Or I can propose a fix for that :)

**Comment by cdujeu** [comment]
Hey, 
WebDAV is a horrible beast... I think we prevent this particularly because of the macOS webdav client that is trying to create tons of hidden files (.DS_Store, etc...). I think that if we change this we should add a specific parameter to avoid changing the default behavior. 
Did you actually try to change that line and recompile the binary?
-c

**Comment by nuxlight** [comment]
I try to comment all parts in code who check hidden folder, but they are no change.
That's seem Webdav library make the same behavior.
