### ISSUE TITLE
Support new Collabora endpoints

### ISSUE THREAD

**Issue by ryansun96** [pydio/cells#378]
Collabora recently released v21 of CODE and Collabora Online, which now uses /browser/dist/cool.html instead of /loleaflet/dist/loleaflet.html and /cool/ instead of /lool/ for websocket. 

It would be great for Pydio to support this new endpoint otherwise people would need to stay on the old 6.x version.

**Comment by cdujeu** [comment]
Hi @ryansun96 thanks for the notice - we'll add this.

**Comment by cdujeu** [comment]
See also https://forum.pydio.com/t/pydio-cells-3-03-and-collabora-online-21-06-integration/4221/7

**Comment by cdujeu** [comment]
I pushed a fix to the master, with a new parameter in the editor.libreoffice plugin config (to switch between v6 and v21+). Would be interested to have feedback ! I’ve left the “v6” by default.
Can you test the last build on Index of https://download.pydio.com/pub/cells/dev

**Comment by cdujeu** [comment]
Fixed in stable now
