### ISSUE TITLE
Problems with structured storage

### ISSUE THREAD

**Issue by mtrstudio** [pydio/cells#381]
I am using the latest cells in docker. I mapped a folder from host system into docker container where cells is running, then use the mapped folder as a structured datasource.  I find it works differently as expected: 

1.  Modify a file in the mapped folder, say "example.pdf", resynchronize to cells manually, then try open "example.pdf" from inside cells, it shows "loading document ...." but it is never opened. (Note the file example.pdf can be opened smoothly before modification and resynchronization )
2.  Put some tags on "example.pdf", all tags are lost when you move it to a new place.

A further question about the flat storage, is there a way to replace or update a document without losing tags? The current behaviour: when you upload a document with the same name, it simply keeps both copies, is it a good idea to prompt the user to choose "keep both or replace"?

Kind of new to cells, there could be something I am missing, please help sort them out, thanks

**Update**: after playing around cells for a while, I figure the issue is cells does not allow users to overwrite documents. In flat storage, if you modify the document manually from your local directory, strange behaviour occurs ! If documents are stored inside cells, you simply cannot overwrite it, uploading the same document (to the same place) twice would give you two copies! The latest version has improved a lot compared with its previous one. But I believe:

1.  it is important to be able to overwrite documents when needed ! 
2. preferably, users should be able to do shallow copying, i.e. only the object itself is copied and deep copying where an object and all its meta data are copied !

**Comment by cdujeu** [comment]
Hello @mtrstudio , can you kindly post in the [forum](https://forum.pydio.com) ? We use github for qualified issues only.
