### ISSUE TITLE
Admin Cells Console unavailable ?

### ISSUE THREAD

**Issue by Salamandar** [pydio/cells#382]
Hi,
I just installed Cells with the latest ARM dev build, and I can't access the cells console. It's just not visible on the drop-down menu :
![Capture du 2022-01-04 16-17-52](https://user-images.githubusercontent.com/6552989/148081098-1cbce0db-08c7-4335-b90d-8c28c4fbf82c.png)

I tried re-adding permissions with `cells admin user set-profile -u admin -p admin` and I even tried to create another admin user, but no luck.

Do you have any idea what's going on ?

**Comment by cdujeu** [comment]
Please use the [forum](https://forum.pydio.com) for configuration questions, thx
