### ISSUE TITLE
[SQL] Server does not answer yet, will retry in 10 seconds...

### ISSUE THREAD

**Issue by DillFrescott** [pydio/cells#385]
I am using the newest version of cells. I've tried it on multiple machines, local and remote mysql databases, using both Linux and Windows and I keep getting this error.

**Comment by DillFrescott** [comment]
I might have found a workaround. The only place it worked was my main pc using xampp's mysql database. So I created the database on that machine, used phpmyadmin's export database feature to export it and import it on the other machine and just redid cell's init process. It seems to have worked for now...

**Comment by cdujeu** [comment]
This should be forum-related issue, thx (https://forum.pydio.com)

**Comment by DillFrescott** [comment]
Sorry sir
