### ISSUE TITLE
Need a way to auto configure database using a config file.

### ISSUE THREAD

**Issue by indivisionjoe** [pydio/cells#389]
Hello.

I am a TrueNAS SCALE user (https://www.truenas.com/truenas-scale/). Pydio-cells was recently implemented for TrueNAS SCALE by the TrueCharts team (https://truecharts.org/).

However, it had to be moved from release to incubator status because there is no independent database solution available for TrueNAS SCALE. They would need to explain the technical reasons for this. But, essentially, they do have databases set up to be installed along with apps that need them. But, they don't have a separate database app that users can directly install and use on TrueNAS SCALE.

In order for them to apply the database setup, they need to be able to configure it via a config file or env vars. Is it possible for you to add such a config perhaps so that it bypasses the database step in the setup wizard if its present and correctly filled out?

I would really like to use Pydio-Cells on my NAS and I am sure many other users would like it as well. There are some other file sharing apps available via TrueCharts. But, imo, the demo for Pydio-Cells looks best.

**Comment by bsinou** [comment]
Hello, 

I would be happy to help on the subject, and I think almost everything is already there -> you have to look in the install yaml direction, **but this is rather a discussion for the forum** ( https://forum.pydio.com ). If we find a bug along the way, we'll come back here and enter a new issue.

Until there, closing this and see you soon in the forum-
