### ISSUE TITLE
Removed and missing option SHARED_FOLDER_SHOW_SEARCH

### ISSUE THREAD

**Issue by corus87** [pydio/cells#390]
Hi,

we were going to update our pydio to the latest version but we noticed a missing function which has been [out comment](https://github.com/pydio/cells/commit/f0e49974cca55d42508942626958996e22f39112) some years ago.

Was or is there a specific reason why "SHARED_FOLDER_SHOW_SEARCH"  was out comment? Because this is a feature we still need. 

Best regards.

**Comment by cdujeu** [comment]
Hi - this is indeed something we could re-implement, as it will no more "impact performances" as indicated in the pydio8 description of the parameter :-).

**Comment by corus87** [comment]
Thanks for the reply @cdujeu 

those are great news you consider to re-implement this feature. Is there something we can do to assist? I guess it's a bit more to do as just un-comment the line?

**Comment by cdujeu** [comment]
definitely more than a simple un-comment :-)

**Comment by 0xMDIV** [comment]
After searching hundreds or thousands of commits in pydio-cells and pydio-core i still cant find the definition of the function/option
