### ISSUE TITLE
Upload failures with CEC

### ISSUE THREAD

**Issue by vmatekole** [pydio/cells#397]
For the past week I have made attempts to migrate from Dropbox (170GB) to Cells. Using Cells sync client has lead to multiple failures. cec was used as an alternative and seemingly works in some cases and not in others. Amongst the folders being copied over is a Cryptomator based vault (6GB+) it contains 1000’s of files and folders due to Cryptomators security architecture. cec fails to upload this folder with an error:

```
  0% [--------------------------------------------------------------------] Transfering 1/310344 files or folders
2022/03/17 19:44:16 Post "https://cells.matekole.com/a/tree/create": context deadline exceeded
```

**Comment by bsinou** [comment]
Duplicate with the forum. Please do not do this.
