### ISSUE TITLE
Server returns emtpy body to put request

### ISSUE THREAD

**Issue by IanPhilips** [pydio/cells#40]
I'm curious if this is intentional: uploading a file via the s3 `putObject` method returns an emtpy body even though the uuid shows up on the server logs. Why doesn't it return the uuid so the client can modify the file later? Otherwise I can't find a way to get a file's uuid.

**Comment by cdujeu** [comment]
Hi Ian
This the S3 protocol. You have to perform a stat afterward to get the file metadata, using the TreeService api. The file is posted to S3, then an event will trigger the internal index synchronisation, so you may have to wait (or use a retry) until the file is appears.
Charles

**Comment by IanPhilips** [comment]
Ahh I see, thanks again Charles. This seemed a bit opaque to me as nothing similar to your advice comes up for google searches like: "get uuid of s3 object following "PUT" operation" or "get metadata of s3 object following "PUT" operation" but this could be my sparsity of gray matter in question here.
