### ISSUE TITLE
Setting SMTP password wipes out pydio-vault.json

### ISSUE THREAD

**Issue by airotaru** [pydio/cells#403]
In **Settings**, when **Mail Engine** is set to **SMTP Server**, any updates to **Connection Password** lead to **pydio-vault.json** being overwritten and all secrets lost.

Affected version: Pydio Cells Home Edition 3.0.7-dev.202203220938

**Comment by cdujeu** [comment]
we are currently looking at it - probably a 3.0.7 soon ;-)

**Comment by cdujeu** [comment]
solved in 3.0.7
