### ISSUE TITLE
timestamp of uploaded files

### ISSUE THREAD

**Issue by ChillDuder** [pydio/cells#407]
Hi, 

i didn't even know if this is a issue or works as designed (version 3.0.6)

if you use the upload functions or drag&drop to the webinterface of pydio to store a file to a flat organized data source the (modification) timestamp of the uploaded file is not stored, instead set to upload time. 
in database as well as on the filesystem directly.

is this intended, or can i do something on my own installation to change that behavior?

**Comment by cdujeu** [comment]
Hi, yes this is expected the timestamp is indeed corresponding to the file creation date **in the server** => upload time !
