### ISSUE TITLE
[Firefox] Invisible input of the login & pass (white text over white bg)

### ISSUE THREAD

**Issue by drzraf** [pydio/cells#410]
1. Fill the login form, using Firefox (99), here using auto-completion
![1](https://user-images.githubusercontent.com/1169926/167682266-ec198514-8baf-4432-b04e-93d354bb5af1.png)

2. Results in (apparently) empty boxes
![2](https://user-images.githubusercontent.com/1169926/167682307-658ba8e3-0dfe-44cd-aab6-2995e30ddadf.png)

3. Actually because of the CSS hiding the text
![3](https://user-images.githubusercontent.com/1169926/167682355-0cd9499c-1cdc-43d5-b277-f684b19849e9.png)

- Affects the ability to connect (many users may simply not understand what's happening)
- Reproducible by @bsinou 
- https://forum.pydio.com/t/invisible-login-text-pass-white-text-bg/4435

**Comment by RenatoSalles007** [comment]
Can confirm the same behavior here with Firefox 104.0.1 on Linux/Ubuntu.

**Comment by cdujeu** [comment]
Can someone try v4 rc5 ?

**Comment by bsinou** [comment]
Tried with the brand new GA v4, and it's much better (even if there are still some room from "aesthetic" improvement...).

![NewLoginForm-KnownUser](https://user-images.githubusercontent.com/1344343/196444020-6b191317-ced2-4e23-8c2e-7c76d6b4e8d4.png)

-> closing
