### ISSUE TITLE
[Question] LDAP Community Implementation

### ISSUE THREAD

**Issue by Dzordzu** [pydio/cells#412]
Is there any chance, that in case of situation when someone prepare a reasonable PR with LDAP implementation, maintainers will be willing to merge it? I know that Ent edition has it. It's quite a crucial feature

**Comment by cdujeu** [comment]
Hello @Dzordzu 

I'll be transparent: as this is already part of the Enterprise Edition, I'm sorry to say that we would not merge it. We do our best to combine an open-source offering with a sustainable business model. We know that there are many discussions in the community about this topic, but our team is small, we love to pay our core developers, and any new feature requires long-term support and internal testing to make sure the quality stays at par...  :-)
Buying a subscription is a way to support the project in the long term. Actually, we created the "Connect" edition, which does provide the LDAP connector without all the other enterprise features, to already offer a cheaper version for small-budget companies! 
If your company is willing to contribute and/or publish testimonials about the software usage, we can also discuss pricing in PM ;-)

Best,
Charles
