### ISSUE TITLE
Error or maybe Notice?

### ISSUE THREAD

**Issue by jeffgoh** [pydio/cells#417]
`2022-06-13T23:19:42.307Z	ERROR	pydio.rest.frontend	Rest Error 401	{"error": "No refresh token"}`
`2022-06-18T00:39:43.699Z	ERROR	pydio.rest.frontend	Rest Error 401	{"error": "No refresh token"}`

I dug thru the code, and I'm thinking this happens whenever someone logs in via the web?  Perhaps it should be a NOTICE instead of an ERROR. I know this is a small thing, but whenever I grep my logs for errors or warnings, this is the only thing that pops up.
If this is really an error though, I'd like to know what the error means.

**Comment by cdujeu** [comment]
hello, indeed it's more a WARN (or why not a NOTICE) than en ERROR. You can safely ignore them.
