### ISSUE TITLE
Cells v4: Detection of private network interface failes

### ISSUE THREAD

**Issue by tfl** [pydio/cells#426]
In Cells 3.x there is a loop over all network interfaces and the first interface
found that matches the (your) definition of a private interface is returned.

With Cells v4 the loop is gone. The first interface found will be tested
and most of the time it will detect a non-private interface resulting in
a warning that there is no private interface, thus it will expose the grpc
API to the public.

I personally would like to have the ability to tell the Cells process which
private interface to use rather then letting the software decide.

**Comment by bsinou** [comment]
Thanks for reporting. We'll have a look at this ASAP.

**Comment by cdujeu** [comment]
Fixed in 685b5d3510b0da25c5228241582c0463f0f50d59
