### ISSUE TITLE
Cells v3.0.9: Failed to build with Go >= 1.18

### ISSUE THREAD

**Issue by tfl** [pydio/cells#427]
Currently it is impossible to build Cells v3.0.9 with Go >= 1.18

If there is Go >= 1.18 then ```go get ...``` does not work anymore.
You have to use ```go install github.com/pydio/cells@v3.0.9``` - but eventually it will fail with

```
go: github.com/pydio/cells imports
        github.com/pydio/cells/broker/activity/actions imports
        github.com/pydio/cells/broker/activity imports
        github.com/etcd-io/bbolt: github.com/etcd-io/bbolt@v1.3.6: parsing go.mod:
        module declares its path as: go.etcd.io/bbolt
                but was required as: github.com/etcd-io/bbolt
```

I cannot downgrade to Go 1.17, I already downgraded from 1.19 to 1.18 on my Arch systems...
(I tested Cells v4 but it's UI does not load. It say's the backend is not ready yet...)

**Comment by bsinou** [comment]
> Currently it is impossible to build Cells v3.0.9 with Go >= 1.18

We are well aware of this. The v3 was our last branch without go modules, and we were hitting the limits of what could be efficiently done with `go vendor` .

> (I tested Cells v4 but it's UI does not load. It say's the backend is not ready yet...)

You should really rather go on this way, the v4 is really near and we are really working hard on fixing the last glitches: could you please give further details on the error? Do you see any relevant log?

**Comment by tfl** [comment]
Regarding the v4 problem: No. While testing, I start cells as cells user like this ```CELLS_WORKING_DIR=/srv/cells ./bin/cells start``` and apart from the error message I described in https://github.com/pydio/cells/issues/426 there is not a single error during startup and browser request. Not even nginx has nothing to complain about. 

```
Binary:
  Package:      Pydio Cells Home Edition
  Version:      4.0.0-dev.20220901112341
  BuildTime:    01 Sep 22 11:23 +0000
  Git Commit:   138e651a6026e1d6fbc81fb5dda65f3f69b4f1f7
  Go Version:   go1.18.4
  OS/arch:      linux/amd64

Drivers:
  Registry:     mem:///registry
  Broker:       mem:///broker
  Config:       file:///srv/cells/pydio.json
  Vault:        file:///srv/cells/pydio-vault.json
  Keyring:      file:///srv/cells/cells-vault-key
  Certificates: file:///srv/cells/certs
  Cache:        bigcache:///cache
  ShortCache:   pm:///shortcache

Networking:
  Hostname:     my hostname here
  Advertise:    my IP

Monitoring:
  Metrics:      false
  Profiles:     false
  ```

Now following the usual startup info messages with two warnings
* admin - admin endpoint disabled
* tls - stapling OCSP{"error": "no OCSP stapling for [127.0.0.1]: no OCSP server specified in certificate"}

I am behind a nginx configured like this

```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name my_alias_hostname; // which is used during configure sites
    client_max_body_size 0;
    proxy_buffering off;

    ssl_certificate      /path/to/fullchain.pem;
    ssl_certificate_key  /path/to/privkey.pem;
    ssl_session_cache shared:SSL:1m;
    ssl_session_timeout  5m;
    ssl_ciphers  HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers  on;

   location / {
        proxy_pass https://127.0.0.1:8080;
        proxy_ssl_verify off;
   }

   location /ws {
        proxy_pass https://127.0.0.1:8080;
        proxy_ssl_verify off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
   }
}
```

configured site from pydio.json

```
"sites": [
      {
        "Binds": [
          "127.0.0.1:8080"
        ],
        "ReverseProxyURL": "https://the same hostname as in nginx's server_name directive",
        "TLSConfig": {
          "SelfSigned": {}
        }
      }
    ]
```

There is no error logged, even nginx does not complain but returns 503
From what I know from 3.x there has to be a valid private network otherwise Cells would not work properly.

**Comment by cdujeu** [comment]
to be retested on next rc please
