### ISSUE TITLE
cells-cal data sync fails

### ISSUE THREAD

**Issue by YannickGagnon** [pydio/cells#43]
When I try to run: "./cells-ctl data sync" I get the following error:

Resync Failed: {"id":"go.micro.client","code":500,"detail":"none available","status":"Internal Server Error"}
[Time taken : 102.336273ms]

I get the error with or without specifying a source. Would you have an idea?

Versions:

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

Cells: 1.2.3

**Comment by YannickGagnon** [comment]
Is this a case where the feature is simply not being implemented yet?

**Comment by cdujeu** [comment]
hi Yannick
It's a bug. Just fixed in master - will be in next release, sorry about that.

**Comment by cdujeu** [comment]
That said, the error you see is normal when not specifying a service name (`--service=pydio.grpc.data.sync.DsName`)

**Comment by YannickGagnon** [comment]
Thanks Charles.

By the way, here's my use case.

We use your cells product to provide files to clients and receive files from client. I need to implement an automatic purge mechanism so that all files are deleted after something like 15/30 days (haven't decided yet). The system allows purging previous versions but not actual files like I described earlier.

So the plan would be to create a script on the serveur to find all files older than the chosen threshold, delete them and run cells-cal data sync to update the index.

Makes sense? Or you already thought of this use case?

Thanks,

**Comment by YannickGagnon** [comment]
Good to know. Thanks.

**Comment by cdujeu** [comment]
Yannick, are you sure of the path parameter ? Did you try without it ?

**Comment by YannickGagnon** [comment]
Yes I did without it first, but I thought that since default path value is /, it could be why it took too long.
Any idea or mean to trace what's happening?

**Comment by cdujeu** [comment]
Anything happening in the server logs when you send the command? Is the data source very « big »?

**Comment by YannickGagnon** [comment]
There is nothing in the Pydio.log or Cells.log located in: ~/.config/pydio/cells/logs
Any other logs I should be check?

Else, there is only one file in the specified (a 15M dmg file) datasource as I'm setting it up for new year deployment.

**Comment by cdujeu** [comment]
Mmm - dumb question, but cells server is started, right?

**Comment by YannickGagnon** [comment]
Yes, it is indeed, but as I said, my cells server is still version 1.2.3, does it make a difference?

**Comment by cdujeu** [comment]
try to upgrade and let's see - it should be painless, there is no specific migrations implied, just the binary differs

**Comment by YannickGagnon** [comment]
Do I just replace both binaries and start cells service again? or there is an upgrade command to run? Cause I did replace the cells binary and now the service appears to be running, but I can't load the website anymore.

**Comment by cdujeu** [comment]
did you wait long enough? can you post the full log after restart?

**Comment by YannickGagnon** [comment]
Alright, I figured it out, here was the issue in the log:

{"level":"error","ts":"2018-12-14T16:03:36Z","logger":"pydio.gateway.proxy","msg":"*******************************************************************"}
{"level":"error","ts":"2018-12-14T16:03:36Z","logger":"pydio.gateway.proxy","msg":"   ERROR: Cannot bind to port 443.   "}
{"level":"error","ts":"2018-12-14T16:03:36Z","logger":"pydio.gateway.proxy","msg":"   You should probably run the following command "}
{"level":"error","ts":"2018-12-14T16:03:36Z","logger":"pydio.gateway.proxy","msg":"   otherwise the main internal proxy cannot start"}
{"level":"error","ts":"2018-12-14T16:03:36Z","logger":"pydio.gateway.proxy","msg":"   and your application will be unreachable."}
{"level":"error","ts":"2018-12-14T16:03:36Z","logger":"pydio.gateway.proxy","msg":"   $ sudo setcap 'cap_net_bind_service=+ep' <path to your binary>"}
{"level":"error","ts":"2018-12-14T16:03:36Z","logger":"pydio.gateway.proxy","msg":"*******************************************************************"}
{"level":"error","ts":"2018-12-14T16:03:36Z","logger":"pydio.gateway.proxy","msg":"Could not run ","error":"listen tcp :443: bind: permission denied"}

I already ran the following command in the past: "sudo setcap 'cap_net_bind_service=+ep' <path to your binary>" Any reason I needed to do it again to work?

But appart from that, it all works now. So thanks you very much for your help.

**Comment by cdujeu** [comment]
Indeed, you have to do it each time you update the binary. The next in-app upgrades starting with 1.2.4 will now show a warning in the interface to remind you of that :-)
So the Resync is working as well?

**Comment by YannickGagnon** [comment]
Yes, it all works out perfectly now. Great work and awesome support.

Thanks
