### ISSUE TITLE
Thumbnails sometimes fail to generate, no method to fix/retry - Pydio Cells 4.0.0 RC4

### ISSUE THREAD

**Issue by wpuckering** [pydio/cells#432]
Sometimes in Pydio Cells 4.0.0 RC4, I've noticed that for whatever reason, some image thumbnails will fail to generate. There doesn't seem to be a way to get them to generate again if they failed the first time.

I think it would make sense to have some kind of job periodically go through all of the images in a data source which do not have thumbnails, and try to regenerate them. Or maybe do something like this as part of data source sync.

It's not reasonable to expect the user to find all images missing thumbnails and manually make a change to them that will cause regeneration to happen (such as renaming a file and renaming it back).

**Comment by cdujeu** [comment]
There is in fact a job for that, but it's only editable with Cells Flows (enterprise edition). Why not adding this as a command line for the Home Edition

**Comment by GwynethLlewelyn** [comment]
See also #302

**Comment by cdujeu** [comment]
we've added a new command `cells admin datasource rethumb` for that task. Still we should better find out why thumbs sometimes fail to generate (if you see any reproducible scenario while you are testing...)
