### ISSUE TITLE
Collabora Online (libre office) plugin wrong works with different domain

### ISSUE THREAD

**Issue by archekb** [pydio/cells#437]
In Collabora Online Plugin settings we can add different domain for document server, but front end component https://github.com/pydio/cells/blob/main/frontend/front-srv/assets/editor.libreoffice/res/js/editor.js do not use this params for url generation, instead it use 
https://github.com/pydio/cells/blob/5fba29c51e4e8f562e39e0ac765431f83a5aae9e/frontend/front-srv/assets/editor.libreoffice/res/js/editor.js#L53

that's mean in result we get url without domain, which (by default) linked with current domain:

```
<iframe style="..." src="/browser/dist/cool.html?host=wss://cloud.examle.com&amp;WOPISrc=https%3A%2F%2Fcloud.examle.com%2Fwopi%2Ffiles%2F2c...88b&amp;access_token=WOB...usteL8&amp;permission=edit"></iframe> 
```
This is wrong if we use document server on different domain. I think it should something like this: 
```
const iframeUrl = `${configs.get("LIBREOFFICE_SSL") ? "https" : "http"}://${configs.get("LIBREOFFICE_HOST")}:${configs.get("LIBREOFFICE_PORT")}${configs.get("LIBREOFFICE_CODE_VERSION") === "v21" ? "/browser/dist/cool.html" : "/loleaflet/dist/loleaflet.html"}`;
```

For fast fixing this problem, if you use Nginx, add redirection to right domain, while bug not fixed:
```
    location /browser/dist/cool.html {
        return 301 $scheme://document.server.domain.here.com$request_uri;
    }
```

I think #379 the same. 

Actual for Pydio Cells version 3 and 4.

**Comment by archekb** [comment]
Of course we should redefined defaults for plugin variables to:
LIBREOFFICE_SSL: current url secure
LIBREOFFICE_HOST: Podio cells host
LIBREOFFICE_PORT: Podio cells port

**Comment by cdujeu** [comment]
Hello @archekb 
In fact I think this is not true. We do use Cells' domain as Cells will already **internally** reverse-proxy those requests to the Collabora document server, whatever that is. We do not want the front-end to directly send requests to the document server. 
Do you actually have a usecase where our code is not working?

**Comment by archekb** [comment]
Hi, @cdujeu, thx for your reply.

After your message, I started configure again, and finally, found solution in your paradigm.

For working document server, we should add document server ws redirect on reverse-proxy:
```
    location /cool/ {
        proxy_pass https://cells:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }
```
I think you should add this to Reverse proxy documentation, here: https://pydio.com/en/docs/kb/deployment/running-cells-behind-nginx-reverse-proxy

And one more: When I change plugin config and return to main page, plugin works with old settings, while we do not restart Cells container, I think it's not right.

**Comment by bsinou** [comment]
I have updated the doc following your advice. May you have a look and tell me if it is better so?

**Comment by abelncm** [comment]
Should i also put collabora behind a reverse proxy? is it necessary?

**Comment by abelncm** [comment]
I have it all in this docker compose file, I am using local.docs as domain name for cells and localhost for collabora so it matches the pydio settings.
I'm using nginx, but i also tried other configs. At best i managed to make the editor open for one file but i can not go and open another file because it get's stuck on server connecting then server disconnected.

Can anyone contribute to my docker compose?

**Comment by cdujeu** [comment]
@abelncm please please, we do not use github for "discussions" as long as a bug is not qualified. 
Could you kindly post [in the forum](https://forum.pydio.com) with a good summary of your context, what works what doesn't , and wait for a couple of days?  We do have working setups with Collabora... 
Thx !
