### ISSUE TITLE
New folder does not appear after creating

### ISSUE THREAD

**Issue by giesmininkas** [pydio/cells#439]
Expected behavior: after creating a new folder, it shows up in web UI.
Actual behavior: newly created folder does not show up. Rest request returns 200. Folder is created in underlying storage.

Cells version: 4.0.1
Storage type: Local file system

Relevant log entry:
```
ERROR   pydio.rest.tree Rest Error 500  {"error": "Put \"http://127.0.0.1:38187/cellsdata/username/cell1/new-folder/.pydio\": context canceled", "SpanUuid": "a07c34c7-67a5-4571-914e-52b2f83e7065", "RemoteAddress": "127.0.0.1", "UserAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36", "ContentType": "application/json", "HttpProtocol": "HTTP/1.1", "UserName": "username", "UserUuid": "cd746254-5493-4f19-95aa-12406cdc597e", "GroupPath": "/", "Profile": "admin", "Roles": "ROOT_GROUP,ADMINS,cd746254-5493-4f19-95aa-12406cdc597e"}
```

**Comment by cdujeu** [comment]
hello @giesmininkas, please kindly post questions in the [forum](https://forum.pydio.com), we only track *qualified* bugs on github! Thx
