### ISSUE TITLE
After docker installation, any upload fails with error 443

### ISSUE THREAD

**Issue by Crown0815** [pydio/cells#442]
I just installed Pydio on Ubuntu 22.04.1 LTS

Whenever I try to upload a file through, e.g., drag-and-drop the upload wizard shows 

```
Upload failed: You are not allowed to upload files here
```

I tried the docker setups from the main documentation (https://pydio.com/en/docs/cells/v4/docker) and the one with "Let's Encrypt"
(https://github.com/pydio/cells/tree/main/tools/docker/compose/lets-encrypt). Both show the same issue.

**Comment by cdujeu** [comment]
hello @Crown0815, please kindly post questions in the [forum](https://forum.pydio.com), we only track *qualified* bugs on github! Thx
