### ISSUE TITLE
File not found when opening shared links via facebook

### ISSUE THREAD

**Issue by HagiaHaya** [pydio/cells#445]
As the title says. Facebook Messenger (desktop) adds `?fbclickid=` to the URL, Pydio can't solve it.
For instance, accessing page via: `pydio.xxx.com/public/xxx?fbclickid=` does:
![image](https://user-images.githubusercontent.com/26824260/200187332-47b82b53-6a68-48d2-8e25-30e67ed30573.png)
but after deleting the addition from Facebook -> `pydio.xxx.com/public/xxx` everything seems to work normally:
![image](https://user-images.githubusercontent.com/26824260/200187436-982b7ca6-136d-4b06-9b84-48f6cc6c3a2a.png)
I found temporary bugfix by using URL shorteners.

I'm using Traefik as a reverse proxy.

**Comment by cdujeu** [comment]
Thx @HagiaHaya  - fixed in 8a98893639b0f24356b5736b00e70731147a7b63, will be shipped in next release.
