### ISSUE TITLE
Datasources can not set to other Drive (In Windows)

### ISSUE THREAD

**Issue by swirtgen** [pydio/cells#446]
Hello, 
Had set all the Data Sources (Cellsdata/Personal/pydiods1) (Thumbnails and versions too) to another Drive in my System (Y:\Cells\data)

Now I Had a Bunch of empty Folders on my drive, but uploaded Files will uploaded to my C: drive, which is a bit dissapointing.

Had create a new Workspace to test it, but Files will still uploading to C: 

So, how can I Change this, that my Files will upload to my 4TB Drive instead to my 256GB SSD...?

**Comment by bsinou** [comment]
Hello, 

can you first please post on the [forum](https://forum.pydio.com) ? and only open an issue here when we are sure it is indeed a bug? 

Thanks for your understanding.
