### ISSUE TITLE
Pydio not picking up the collabora's host in iframe

### ISSUE THREAD

**Issue by abelncm** [pydio/cells#456]
I configured collabora host to local.office but when i open a docx file instead of mounting local.office, it mounts local.docs which is my pydio domain.

I get something like this https://local.docs/browser/dist/cool.html?host=wss://local.docs&...
instead of this https://local.office/browser/dist/cool.html?host=wss://local.docs&...

The latter when i open in new tab it works. I don't know why Pydio is not picking the right host from the settings of collabora host!!!

Can you help me fix this issue?

**Comment by cdujeu** [comment]
did you check https://github.com/pydio/cells/issues/437 
In any case, please use the Forums (https://forum.pydio.com) instead of opening issues, thanks !

**Comment by abelncm** [comment]
@cdujeu I managed to make it work through proxy. But i cannot open more than one file to edit. It always gives me server connecting, then server disconnected.
Can you point me in the right direction?
