### ISSUE TITLE
Cells only shows my login name instead of the name property

### ISSUE THREAD

**Issue by tfl** [pydio/cells#458]
After I logged into Cells my login name is shown top left. I expect my public name to be shown there, which I can set by my own or was set by administration...
![cells-error](https://user-images.githubusercontent.com/228038/213576815-1124d460-0f0c-48e9-a0db-73119238491d.jpeg)

**Comment by tfl** [comment]
I have to admit: `TF` ist NOT my real login name. It shows my initials top left, the username bottom right! I expect bottom right username to be shown top left. And do not create some made-up username, dammit! Nowhere in my system is a `TF`!

**Comment by cdujeu** [comment]
please use the [Forums](https://forum.pydio.com) to ask this kind of question, it is not a qualified bug. 
thx !
