### ISSUE TITLE
Public link button doesn't appear in Outlook email client

### ISSUE THREAD

**Issue by jragathe** [pydio/cells#459]
_Note: This issue tracker is only used for reporting **qualified bugs**. Use [Pydio Forums](https://forum.pydio.com) for support or feature requests: first-start, install, or config-related troubleshootings will be ignored and closed! Otherwise, please **fill all sections below**._  

First we start on Pydio Forum and create a topic which is the link below and they ask us to open a bug report.

[The public link is removed from client Outlook email](https://forum.pydio.com/t/the-public-link-is-removed-from-client-outlook-email/4944)

**📝 Describe the bug**

When sending email with a public it doesn't appear on client Outlook (any version). The issue is a trunk email without the Pydio link on the email if we open with a Outlook Client (MS Office 2016 or 2019).

However, we saw that if we open the same email from Outlook Web Access (with Chrome or Edge) the link appear correctly. 

So we check on the source code of email received from the Outlook client and we can see (printscreen) that the Pydio part is in comment. It is like a bad interpretation of the html email send by Pydio to Client Outlook.

![image](https://user-images.githubusercontent.com/124671218/217205199-16b67d87-886a-4e5a-9017-fee7c02c0b3f.png)

**⚙️ How-to Reproduce**

1. Create a Pydio email with public link
2. Open with an "Outlook Client"
3. See error = no link on the client email
4. Open the same email in a web base solution you will see the link.

**🩺 Environment / Setup**

Complete the following information:

Server Versions:
 - Cells Version 4.1.0
 - MariaDB/MySQL version
 - Server OS: Ubuntu 22.04
 - Other dependencies: None

Client used for testing: 
 - Browser: Chrome, Edge, Safari
 - Client OS: Windows 10 & 11
 - Client Outlook: MS Office 2016 & 2019
 
Additional context:
 - Datasource type : flat/structured, storage type, etc... 
 - Add any other context about the problem here.

**Comment by jragathe** [comment]
May I ask you if you plan to fix the bug on Q1 ?
Best regards,
JRA

**Comment by JeffVH** [comment]
Can I add that multiple e-mail templates are impacted?
We experience the same behavior with the "forgot password?" link.
Reset password links do not work in Outlook Desktop (My version: Microsoft® Outlook® voor Microsoft 365 MSO (Versie 2301 Build 16.0.16026.20002) 64 bits).
We are using Pydio Cells 4.1.1.
The same e-mail opens without issues in outlook on IOS or the webmail.

If preferred I can remove this comment and add a new thread.

Thank you!
Kind Regards,
Jeff

**Comment by cdujeu** [comment]
we'll definitely investigate this asap

**Comment by bsinou** [comment]
@JeffVH @jragathe we think we have found and fixed the problem.
Could you give a quick try using the latest dev build: https://download.pydio.com/pub/cells/dev/ ?

**Comment by jragathe** [comment]
As discussed from the forum, this works for me too. Thx!
Kind regards,
Jean-Raoul

**Comment by bsinou** [comment]
The fix is included in the 4.1.2 that has just been released. 
Feel free to update your instances. You should be able to update from the 4.1.2-devxx version to the released one directly from the web admin, if necessary.

For the record, the flag is configurable. You can now choose to explicitly disable CSS in-lining for mails or not , via the admin console with advanced parameters enabled in `Application Parameters / Mailers`. There is a check box. 

In your case, you have to tick it.

BTW, thanks for the quick feedback last week: I forgot to say it before, but it has been seen and appreciated! Thanks.
