### ISSUE TITLE
Upload of files with percent sign within filename not possible!

### ISSUE THREAD

**Issue by raidroGS** [pydio/cells#466]
**Description**
Files with percent sign within the filename can be created using **New empty file**, f.e. test%1%.txt.
 * Uploading of such a file is not possible, i.e. file is shown after upload in the target directory. After refreshing the directory, the file vanishes.
* cells-sync raises an error.

**⚙️ How-to Reproduce**

Upload any file with a percent sign within the filename, f.e. test%2%.txt

**🩺 Environment / Setup**

Server Versions:
 - Cells 4.1.2
 - MariaDB 10.9
 - Server OS: Debian bullseye

Client used for testing: 
 - Browser: chromium, firefox
 - latest cells-sync client on debian bullseye
 
Additional context:
 - Datasource type : flat storage

**Comment by raidroGS** [comment]
cells-sync error reported in https://github.com/pydio/cells-sync/issues/52 from another user

**Comment by raidroGS** [comment]
Any solution on the way for this problem?

**Comment by cdujeu** [comment]
hi @raidroGS not yet - we are focused on fixing other stuff ATM.

**Comment by raidroGS** [comment]
Any advices where to look in the source to fix the problem?

**Comment by cdujeu** [comment]
frankly speaking not really - we would have to check every single layer (from caddy reverse proxy to minio storage...)

**Comment by cdujeu** [comment]
i'll have a look and keep you posted

**Comment by cdujeu** [comment]
Hum, it seems like upgrading caddy to their HEAD (caddy acts our front reverse proxy) fixes the issue. Testing that on a custom branch right now. stay tuned.

**Comment by raidroGS** [comment]
Bug is fixed in version 4.3.0!

Thank You very much!
