### ISSUE TITLE
Error when sharing a folder

### ISSUE THREAD

**Issue by jaimedelano** [pydio/cells#485]
Trying to access public link I get this error message in my browser console:

Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    Vu https://my.domain.name/public/plug/gui.ajax/res/dist/core/DistLib.min.js?v=6d1a72c5364c3d26d2ce7f86064609e0:2
    p https://my.domain.name/public/plug/gui.ajax/res/dist/core/DistLib.min.js?v=6d1a72c5364c3d26d2ce7f86064609e0:2
    m https://my.domain.name/public/plug/gui.ajax/res/dist/core/DistLib.min.js?v=6d1a72c5364c3d26d2ce7f86064609e0:2
    Ei https://my.domain.name/public/plug/gui.ajax/res/dist/core/DistLib.min.js?v=6d1a72c5364c3d26d2ce7f86064609e0:2
    Fa https://my.domain.name/public/plug/gui.ajax/res/dist/core/DistLib.min.js?v=6d1a72c5364c3d26d2ce7f86064609e0:2
    Yl https://my.domain.name/public/plug/gui.ajax/res/dist/core/DistLib.min.js?v=6d1a72c5364c3d26d2ce7f86064609e0:2
    Du https://my.domain.name/public/plug/gui.ajax/res/dist/core/DistLib.min.js?v=6d1a72c5364c3d26d2ce7f86064609e0:2
    Tu https://my.domain.name/public/plug/gui.ajax/res/dist/core/DistLib.min.js?v=6d1a72c5364c3d26d2ce7f86064609e0:2
    Eu https://my.domain.name/public/plug/gui.ajax/res/dist/core/DistLib.min.js?v=6d1a72c5364c3d26d2ce7f86064609e0:2
    gu https://my.domain.name/public/plug/gui.ajax/res/dist/core/DistLib.min.js?v=6d1a72c5364c3d26d2ce7f86064609e0:2
    pu https://my.domain.name/public/plug/gui.ajax/res/dist/core/DistLib.min.js?v=6d1a72c5364c3d26d2ce7f86064609e0:2
    Qu https://my.domain.name/public/plug/gui.ajax/res/dist/core/DistLib.min.js?v=6d1a72c5364c3d26d2ce7f86064609e0:2
    os https://my.domain.name/public/plug/gui.ajax/res/dist/core/DistLib.min.js?v=6d1a72c5364c3d26d2ce7f86064609e0:2
    ku https://my.domain.name/public/plug/gui.ajax/res/dist/core/DistLib.min.js?v=6d1a72c5364c3d26d2ce7f86064609e0:2
    os https://my.domain.name/public/plug/gui.ajax/res/dist/core/DistLib.min.js?v=6d1a72c5364c3d26d2ce7f86064609e0:2
    render https://my.domain.name/public/plug/gui.ajax/res/dist/core/DistLib.min.js?v=6d1a72c5364c3d26d2ce7f86064609e0:2
    n https://my.domain.name/public/plug/gui.ajax/res/dist/libs/PydioReactUI.min.js?v=6d1a72c5364c3d26d2ce7f86064609e0:2
DistLib.min.js:2:806058

**Comment by cdujeu** [comment]
@jaimedelano  - you should know it by now :-) : please first post in the forum, giving more info about your setup.
