### ISSUE TITLE
Cells ( v4.2.0) does not build on Go 1.20

### ISSUE THREAD

**Issue by Hukadan** [pydio/cells#486]
The README indicates that Go language v1.18 or **higher** is needed, but Cell does not build on Go 1.20 due to the (indirect) quic-go dependency. Here is the error message:
```
# github.com/lucas-clemente/quic-go/internal/qtls
../../../../go/pkg/mod/github.com/lucas-clemente/quic-go@v0.29.0/internal/qtls/go120.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.20 yet. For more details, please see https://github.com/lucas-clemente/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.20 yet. F...) as int value in variable declaratio
```
**⚙️ How-to Reproduce**
Build with Go 1.20

**🩺 Environment / Setup**

Server Versions:
 - Cells Version : v4.2.0
 - MariaDB/MySQL version: N/A
 - Server OS: OpenBSD (-current)
 - Other dependencies: N/A

Client used for testing: N/A 

Additional context: None

**Comment by cdujeu** [comment]
Hi @Hukadan thanks for reporting.
We'll give a go with an upgrade of the quic-go library.
-c

**Comment by cdujeu** [comment]
Ok, that was not that simple. 
Finally done, the main branch is now building on go20/21
