### ISSUE TITLE
Error “Pydio is not defined” when run build-core command in gui.ajax folder

### ISSUE THREAD

**Issue by HaiyangZhang1994** [pydio/cells#493]
_Note: This issue tracker is only used for reporting **qualified bugs**. Use [Pydio Forums](https://forum.pydio.com) for support or feature requests: first-start, install, or config-related troubleshootings will be ignored and closed! Otherwise, please **fill all sections below**._  

**📝 Describe the bug**

When I try to run “pnpm run build-core” under folder gui.ajax and then make all, seems like the project start and get error “error loading core/pydio.min.js?v=8d99e3b8bcc1269270e895514b7d9833:Pydio is not defined” from webpage, does anyone has the same issue?

**⚙️ How-to Reproduce**

1. Use terminal enter gui.ajax's folder
2. Run "pnpm run build-core"
3. Run "make all" under main folder
4. Run "./cells start" under main folder

**🩺 Environment / Setup**

Complete the following information:

Server Versions:
 - Cells Version 4.2.2
 - MariaDB/MySQL version MySQL 8.0.33
 - Server OS: macOS 12.3.1
 - Other dependencies None

Client used for testing: 
 - Browser chrome Version 114.0.5735.133
 - Client OS / mobile device, etc...
 
Additional context:
Here's the screenshot
<img width="510" alt="image" src="https://github.com/pydio/cells/assets/44517160/75b65218-ccad-40d6-972f-e192baaf9882">

<img width="1122" alt="image" src="https://github.com/pydio/cells/assets/44517160/98f6368f-e171-43e1-a6a4-f89ddee701bb">

<img width="1116" alt="image" src="https://github.com/pydio/cells/assets/44517160/078c80a6-ee4d-4d1f-9495-d5f71bfb4b80">

**Comment by HaiyangZhang1994** [comment]
@cdujeu

**Comment by cdujeu** [comment]
hello, can you give more context why you want to re-build ? 
Did you also `pnpm run build-libs` and `pnpm run build-boot` ? 

Maybe first try to `make dev` (will use the local JS instead of embed it inside the binary) to validate your JS changes
Also do not forget to env NODE_ENV=production before rebuilding the JS to make sure it is minified

**Comment by HaiyangZhang1994** [comment]
> hello, can you give more context why you want to re-build ? Did you also `pnpm run build-libs` and `pnpm run build-boot` ?
> 
> Maybe first try to `make dev` (will use the local JS instead of embed it inside the binary) to validate your JS changes Also do not forget to env NODE_ENV=production before rebuilding the JS to make sure it is minified

Hi cdujeu, thanks for the reply, actually I tried `pnpm run all` at first since I made some changes in gui.ajax to adjust some text, but it failed so at last I found that the problem will occur when I run `pnpm run build-core`

I just tried `pnpm run build-core` and then run `make dev`, but it still failed

**Comment by HaiyangZhang1994** [comment]
Also I just set `NODE_ENV=production` when I run webpack.core.js, but I still got Pydio is not defined

**Comment by HaiyangZhang1994** [comment]
@cdujeu 
Hi cdujeu, just found that the bug is from `pydio.boot.min,but` dont find where the `Pydio` is defined

<img width="766" alt="image" src="https://github.com/pydio/cells/assets/44517160/066e72a1-6e2b-4a0b-b8ca-e90642999159">

**Comment by cdujeu** [comment]
mmm, if you change gui.ajax, you do not need to recompile the core actually - so maybe try reverting the code ?

**Comment by HaiyangZhang1994** [comment]
> mmm, if you change gui.ajax, you do not need to recompile the core actually - so maybe try reverting the compiled version of the core lib ?

Yeah I just revert the compiled version and everything works well right now, just a little bit curious why rebuild it will cause this bug🤔

**Comment by chaosue** [comment]
this may be a webpack version problem, refer to https://www.ginkonote.com/users/flo/articles/migration-guide-to-webpack-5@javascript, _arguments objects is not available in arrow function._

I resolved this by modify `frontend/front-srv/assets/gui.ajax/res/js/core/index.js:178` as below:
``` js
        return originalRequire.apply(this, libName);
```
