### ISSUE TITLE
How do I connect this to an existing mariadb instance using the docker variant

### ISSUE THREAD

**Issue by jxsl13** [pydio/cells#51]
How do I connect this to an existing mariadb instance using the docker variant?

I'm running a Nextcloud instance for testing purposes and want to use the same already existing Maria DB database in order to not have multiple database containers running.

I seem not to have found much about configuring this using docker images.

I'm using the normal `docker run` command for configuration purposes.

my Nextcloud configuration/ set is based on this: [my openKB](https://help.johnbehm.de/kb/i2jfyRAf2GTpe5T3)

I want to use the database created there with a simple docker run command, preferably with some equivalent environment variables in order to directly configure the Pydio installation?

My command so far:

```
docker run \
	--name=pydio_cloud \
	-p 127.0.0.1:9080:8080 \
	-v /var/lib/pydio:/root/.config/pydio/ \
	--network=basic-bridge \
	--link mariadb_database:mariadb \
	-e CELLS_BIND=localhost:9080 \
	-e CELLS_EXTERNAL=pydio.johnbehm.de:80 \
	-e CELLS_NO_SSL=1 \
	-e MYSQL_HOST=mariadb \
	-e MYSQL_ROOT_PASSWORD=XXXXX \
	-e MYSQL_DATABASE=cells \
	-e MYSQL_USER=pydio \
	-e MYSQL_PASSWORD=XXXXX \
	pydio/cells
```

A caddy reverse proxy that's running on the host machine then should do the rest, as multiple subdomains are managed by that one caddy server.

I'm not quite sure, whether any of those mysql variables actually have any influence on Pydio Cells.
edit:
looking at the entrypoint.sh these environment variables don't seem to influence the direct behavior.
best regards.

**Comment by softtech-geoff** [comment]
AFAIK you'll get more bandwidth on this kind of question in the forums; this issues list is for items which are definitely bugs.  
That said, as long as your MariaDB container is set up to support connections (first google hit [here](https://medium.com/@jaaq/making-docker-containers-talk-to-each-other-by-hostname-using-container-networking-94835a6f6a5b)), you should be able to specify its hostname in the setup screen.

**Comment by cdujeu** [comment]
to be re-opened in forum.pydio.com if required
