### ISSUE TITLE
Password change fails when forcing MFA at the same time 

### ISSUE THREAD

**Issue by JJedrasik** [pydio/cells#516]
**📝 Describe the bug**

Forcing MFA on initial sign on, as well as a password change, causes the password change to be ineffective. Requires the password to be changed twice. 

**⚙️ How-to Reproduce**

Steps to reproduce: 

1. Enable MFA - and force MFA on all accounts (In my case it was admin, standard)
2. Create a new user
3. Force password change for that user
4. Sign in as the newly created user - you will be first asked to setup MFA, and then to change your password. You will then be kicked back to the login screen to sign in again. 
5. Try to sign in with the new password - it will fail. You will have to use the original password you set when creating the account. 
6. You will then be asked to change the password AGAIN - this time it will change successfully. 

**🩺 Environment / Setup**

Complete the following information:

Server Versions:
 - Cells Version 4.3.0 - ENT 
 - Default MariaDB shipped with Debian below 
 - Debian 11

Client used for testing: 
 - Chrome

**Comment by cdujeu** [comment]
Hello @JJedrasik 
Thanks for submitting. However that is a Cells Enterprise issue, could you please kindly contact the support instead of posting here in the public repository?
Thank you - i'm closing this for now.
