### ISSUE TITLE
SIGSEGV on start when no interface with private IP present

### ISSUE THREAD

**Issue by wolf-box** [pydio/cells#52]
Cells segfaults on start on a shared hosting service.

As analyzed by "mzch" on the forums: "cells checks whether there is an interface with a private IP or not around 47-49 in extractor.go. As a result, if the machine doesn’t have any private IPs like my VPS, func extractAddress() returns error, and func genSrv() returns nil, but func Init() in service.go does not check a returned value, so it causes Segmentation Fault. This is an obvious bug."

See original post here: https://forum.pydio.com/t/pydio-cells-not-working/1182/39

**Comment by cdujeu** [comment]
@ghecquet can you have a look at this ? we may log.Fatal with a very clear an descriptive error here?

**Comment by cdujeu** [comment]
Fixed in 1.4.1
