### ISSUE TITLE
Web Interface Menu point of return to main page from cells console are missed if turn off home section

### ISSUE THREAD

**Issue by archekb** [pydio/cells#564]
**📝 Describe the bug**

1) You can't return from Cells admin console to user interface, if turn off `Home` (maybe with `Directory`) section for user. 
![image](https://github.com/pydio/cells/assets/47732882/9719ace4-bcf8-4304-ab91-a223787535d3)

2) Admin can't turn on `Home` and `Directory` access for users, if it was turned off. No matter to Admin or User. The pointer is crossed and have no reaction for click action.
![image](https://github.com/pydio/cells/assets/47732882/141f70db-cc72-4a43-98c3-042b5f385da8)
![image](https://github.com/pydio/cells/assets/47732882/029038b3-6f05-4ca2-86de-b4f9666ee1f1)

**⚙️ How-to Reproduce**

1. Go to Cells Admin Console
2. Click on `People`
3. Select a User -> `Pages`
4. Turn off access for `Home` and `Directory`
5. Refresh page

**🩺 Environment / Setup**

Complete the following information:

Server Versions:
 - Cells Version 4.4.0
 - Server OS: Ubuntu 22.04
 - Other dependencies: NginX

Client used for testing: 
 - Browser Chrome
 - Client OS: Ubuntu 24.04

**Comment by cdujeu** [comment]
Fixed in code, added a "My Workspaces" link in the menu. Will be in the next release ;-)

**Comment by cdujeu** [comment]
closing, a "My Workspaces" menu has been added in 4.3.3
