### ISSUE TITLE
Impossible to make Pydio work with collabora online

### ISSUE THREAD

**Issue by tomakorea** [pydio/cells#568]
I followed the guide here : https://pydio.com/en/docs/cells/v4/collabora-online

However, me and 2 other people with different hardware configurations and server setups (I have a Raspberry Pi5, the others a PC X64 server) couldn't make it work. Maybe something missing in the guide, or it should be more "step by step".
After setting up correctly the collabora online, setting up the host and ports in the plugin section, I came back to my pydio account, I made an excel97 file and and odt file, when I try to open one of the other, it just cameback to the main window, collabora isn't loading at all. I asked 3 other people to try, all with the same results.
Could you please update the guide with more detailed instructions? or more step by step process? or is the guide outdated and this feature doesn't work anymore?

Thank you !

**Comment by jadedhound** [comment]
I can confirm that Pydio + Collabora Online does indeed work. Are you by any chance using docker as the installation method (I am), because if so, what does it yield when you:
```bash
docker logs <pydio container name>
```

**Comment by cdujeu** [comment]
Hello @tomakorea, welcome to the community and thanks for posting. However, if not already done, please use the [FORUM](https://forum.pydio.com) to ask such question. Github is only for real bugs. 
Thx !
