### ISSUE TITLE
Collabora is used in pydio cells, and the Collabora interface cannot display Chinese.

### ISSUE THREAD

**Issue by bmyhelpcode** [pydio/cells#580]
**Hello, this is my basic environment configuration:**

1. Operating system: Ubuntu Server latest 24.04 LTS x86_64
2. pydio cells version: v4.4.3
3. Collabora version: v24.04.6.1.1

As mentioned in the question, I'm using Collabora in pydio cells. The Collabora interface cannot display Chinese. After investigating the pydio cells code, I found that it was caused by a line of code in pydio cells.
![1](https://github.com/user-attachments/assets/ad252b7c-ee67-4b8f-b6a2-49be93d7f42d)

```javascript
 h.split && (h = h.split("-")[0])
```
---
This line of code will change the value of the **h** variable from **zh-cn** to **zh**, and the parameter that Collabora needs to pass in the address bar to switch the interface language is **lang=zh-cn**, which directly causes the value of the lang parameter passed to Collabora to be incorrect. , Collabora cannot display the Chinese interface correctly
![2](https://github.com/user-attachments/assets/e1b87982-dd93-458c-84a6-6331537d09d1)

---
When I copy the address of the iframe to the browser address bar and modify the **lang** parameter to **zh-cn**, Collabora displays the Chinese interface correctly.

![3](https://github.com/user-attachments/assets/6f057ac3-7909-4ad5-922d-2d2e16d6f911)

---
I tried modifying the code like this and Collabora works fine, but this is just validation of my idea, not the final solution.
![4](https://github.com/user-attachments/assets/acee1143-1a97-47bc-982f-2ff7ed12ca6b)

How should I solve this problem in pydio cells? Looking forward to reply, thank you.

Thanks to the author for providing such an excellent project.

**Comment by cdujeu** [comment]
hi @bmyhelpcode thanks for submitting
we'll add an edge case for zh-cn, as for other languages (en, fr...) collabora expects only the first part.
keep you posted

**Comment by bmyhelpcode** [comment]
@cdujeu Thank you for your reply. After the case is added, if you have time, please let me know the latest solution. Thank you.

**Comment by bmyhelpcode** [comment]
@cdujeu Thanks for the reminder, I just saw the submitted code. I'm going to test

**Comment by bmyhelpcode** [comment]
> (already commited if you want to test from the code)

I just tested the code and it ran successfully without any problems, thanks for the help!

**Comment by bmyhelpcode** [comment]
> cool, will be in v4.4.4

Looking forward to the release of the new version and thanking the team for their hard work
