### ISSUE TITLE
Versioning with docker

### ISSUE THREAD

**Issue by joalmjoalm** [pydio/cells#6]
Hi 
I have installed Cells in a docker environment on a ubuntu host and the installation is up and running.
I have created a bind volume between a directory on the host and a directory in the container.
Then add this dir in the container as a datasource.
The files added to the dir on the host appear in the workspace, also changes to content in an existing file on the host appears in workspace.
But the timestamp of modification is NOT pickup by Cells, not even after re-syncing the datasource.
Timestamp in container is correct but not in workspace,
So the versioning is not working and I guess its caused by the fact that changed timestamp in container is not pickup up by Cells. 
please investigate.
/Jonas

**Comment by cdujeu** [comment]
Hi Jonas, 
Thanks for reporting, we'll try to reproduce that and keep you posted.
Charles

**Comment by cdujeu** [comment]
@bsinou could you have a look at that one : is creating a datasource on a binded volume what we do in our standard setup ?

**Comment by KungFu-Kenny** [comment]
Hi,
i tested on your most recent version (1.2.3) and i did not encounter the issue,
when i did a modification the timestamp was always updated on both the GUI and the VOLUME(local storage) and also the versioning worked on my end i did not have trouble with it.
