### ISSUE TITLE
Pydio vs minio vs dropbox

### ISSUE THREAD

**Issue by Abdukahhor** [pydio/cells#97]
Hello 

There are a lot of such programs. What are the benefits and features of Pydio? Could you compare these programs? I do not find a lot info in blogs like medium.com, etc.

**Comment by cdujeu** [comment]
[same as other issue => next question please please head to the forum, thanks!]
Good question, could make an interesting article indeed. 
To make it short
- Dropbox : you do not host your document, they do. So you're not really sure of what they do with your data... :-). Plus in some case you keep uploading / downloading stuff to / from the cloud whereas you would benefit of having a nearshore server for that.
- Minio : a lightweight s3 clone that can be deployed on premise. Can provide some similar features to pydio, but it's much more developers-oriented. It's really a solution for storage people who want to easily switch an existing S3-based infra to an on-premise infra. Pydio actually uses minio as the storage layer
- Pydio : a full-fledge collaboration platform to be deployed on premise (or on any cloud of your choice). Provides much more high-level features (auth, role-based acls and security policies, notifications, etc..). Drop-in replacement for google drive or equivalent solutions.
Cheers
Charles
